### ISSUE TITLE
menu doesn't work as expected

### ISSUE THREAD

**Issue by codemonkeynorth** [corcel/corcel#197]
as per this post https://github.com/jgrossi/corcel/issues/9, when creating menu items `$item->title` or `$item->post_title` does not pull through the expected menu entry. also `$item->slug` pulls through the slug of the  menu item, not the post it relates to

the following issues seem to be present
- menu item does not show title unless it is changed from the original page name
- WP creates a nav_menu_item entry in wp_posts so using $item->slug etc gets the slug of the menu item, not the slug of the post the menu item is meant to point to

for every menu item I ended up creating a custom link (instead of a Page/Post/Category menu item) and then linking to `$item->meta->_menu_item_url`

what would be the correct way to loop through a WP menu with Corcel and get the links to my pages?

thanks
j

**Comment by jgrossi** [comment]
Hi @codemonkeynorth! Are you using `nav_items` property to loop through?

**Comment by codemonkeynorth** [comment]
like this
```php
$menu = Menu::slug('main')->first();
foreach($menu->nav_items as $item) {
    echo("item:".$item->post_title."<BR>");
}
```

if i add a page to the menu for instance, for that menu item:#
ID=61, 
post_title is blank 
post_name is 61, 
post_type=menu_nav_item

that is the data assigned to the nav item, not to the post it refers to.
post_title only gets a value if I change it from the default Page title.

from what I can see the likely reference to the actual page (whose ID=2) is in `wp_postmeta` table

post_id=61 (matching my menu entry)
meta_key = _menu_item_object_id
meta_value = 2 (matching my page ID)

I'm not sure how to connect these up in the nav loop. I'm assuming I could do something with $item->_menu_item_object_id, but I'm not sure that's always the relevant data, for instance when I add a custom link to the menu rather than a page/post (in the latter case, the URL I need is in meta_key _menu_item_url)

thanks
j

**Comment by jgrossi** [comment]
What `$item->nav_items()` returns to you?

**Comment by codemonkeynorth** [comment]
do you mean `($menu->nav_items());`

it seems to get stuck in recursion

**Comment by jgrossi** [comment]
Yes, it is. What `$menu->nav_items()` prints?

**Comment by codemonkeynorth** [comment]
that gets stuck in a recursive loop

**Comment by codemonkeynorth** [comment]
using a default 4.5.2 Wordpress and Laravel 5.2, with `print_r($menu->nav_items)` 
http://pastebin.com/sTN8Sgus

(the only item I added to my menu here is my page called "Sample Page".. you'll see that text doesn't appear in the data, but you can see this

```php
[meta_key] => _menu_item_object_id
[meta_value] => 2
```

(Sample Page is always ID=2 on fresh WP install)

thanks
j

**Comment by codemonkeynorth** [comment]
I was just looking at the code for Timber/Twig.. this is how they get the link for instance

might be worth looking at...
https://github.com/timber/timber/blob/63fe60ba18c6fce5d545983334af3f752c7c2755/lib/MenuItem.php

```php
public function link() {
  if ( !isset($this->url) || !$this->url ) {
    if ( isset($this->_menu_item_type) && $this->_menu_item_type == 'custom' ) {
      $this->url = $this->_menu_item_url;
    } else if ( isset($this->menu_object) && method_exists($this->menu_object, 'get_link') ) {
      $this->url = $this->menu_object->get_link();
    }
  }
  return $this->url;
}
```

**Comment by schrink** [comment]
Same issue here.

**Comment by jgrossi** [comment]
Hi @codemonkeynorth sorry about the late answer. I've been a little busy last days. 

Did you solve your issue? Is there anything I can do to help? Cheers

**Comment by codemonkeynorth** [comment]
I worked around it by hardcoding all the links as custom links, rather than using the standard post/page-based entries in the menu setup

but this is not ideal

thanks
j

**Comment by jakejohns** [comment]
This is likely not particularly useful a it's quite hacky/sloppy, but I'm dropping it here for others and my own future reference.

I think th desired effect here is to get the *actual* `Post` record based on the menu. I'm currently hacking it like this for now:

```php
<?php
// @codingStandardsIgnoreFile

use Corcel\Post;

class NavPoint extends Post
{

    public function getObjectIdAttribute()
    {
        return $this->meta->_menu_item_object_id;
    }

    public function getObjectAttribute()
    {
        $type = $this->meta->_menu_item_object;

        switch($type) {
        case 'page':
            return \Corcel\Page::find($this->objectId);
            break;
        case 'post':
            return \Corcel\Post::find($this->objectId);
            break;
        case 'custom':
            return $this;
        default:
            $msg = sprintf('Invlaid object type: "%s"', $type);
            throw new \Exception($msg);
            break;
        }
    }
}


$post->registerPostType('nav_menu_item', NavPoint::class);

//...

foreach ($menu->nav_items as $item) {
    var_dump($item->object->toArray());
}
```

Obviously this is less than ideal, I just noticed that I can get the object type and post_id in the meta properties. Again, this solution is very suboptimal, generating far more DB trips than desired.

I really don't like WP or Eloquent, I'm just currently forced to use them. That being the case, my insight here is quite limited. 

Does anyone have any **good** ideas? This is clearly not one.

**Comment by harpster604** [comment]
Same problem here. Unable to use Posts, Pages, or Categories in a menu.

**Comment by lightning229** [comment]
I have same problem, and my solution is find term name by meta _menu_item_object_id:

```php
$menu = \Corcel\Menu::slug('primary')->first();

$menuArray = array();

foreach ($menu->nav_items as $item) {

	$parent_id = $item->meta->_menu_item_menu_item_parent;
	
	if ($item->post_title == '') {
	
		$term_id = $item->meta->_menu_item_object_id;
		
		$term = \Corcel\Term::find($term_id);
		
		$item->post_title = $term->name;
		
	}
	
	$menuArray[$parent_id][] = $item;
	
}
```

**Comment by ZapevalovAnton** [comment]
Same problem.

**Comment by ZapevalovAnton** [comment]
Why nav_items method in the TermTaxonomy model??? Why not in Menu model??

**Comment by ZapevalovAnton** [comment]
@jgrossi At you all works normally?

**Comment by jgrossi** [comment]
Hi @ZapevalovAnton @lightning229 @harpster604 @codemonkeynorth @jakejohns. You're right, the Menu feature should be improved to a better result, using a better OOP approach.

What do you think on working together with a fix for that? Can anyone send a PR or even just an idea about that? Thanks!

**Comment by jgrossi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix menu issues](https://trello.com/c/AyFl11jz/3-fix-menu-issues)

**Comment by jgrossi** [comment]
Hi @ZapevalovAnton @lightning229 @harpster604 @codemonkeynorth @jakejohns. I'm fixing this issue and cleaning up the code for better understanding. I need your help, can anyone send me a slice of the `wp_postmeta` and `wp_posts` tables with those records related to a menu? I'm gonna change the logic in the code to make it work.

I'd be better to have a complete SQL code, like a Menu with Post, Page and Category, for example.

Thanks!

**Comment by jgrossi** [comment]
Just to let you know, there's not test coverage for this yet, so I'm gonna understand your needs and then right tests to make sure everything is working.

**Comment by jgrossi** [comment]
Hey @ZapevalovAnton @lightning229 @harpster604 @codemonkeynorth @jakejohns. Just to let you know the menu issue is fixed on `2.4` branch. I'm working on a new version of Corcel and we're going to match Laravel release: so `Laravel 5.0 => Corcel 2.0, .. Laravel 5.4 => Corcel 2.4`. For now there's no tag in the `2.4.*` release yet, but I'm gonna do that soon.

I've added some new unit tests, even for menu. Now you can work with menu like this:

```php
$menu = Menu::slug('main-menu')->first();
foreach ($menu->items as $item) { // each $item is an instance of Corcel\MenuItem class
    // ->instance() returns an instance of Post, Page, TermTaxonomy or CustomLink
    echo $item->instance()->title; // for post for example
    echo $item->instance()->slug; // for category/term for example
    echo $item->instance()->item_text; // for custom links
}
```
That's all. If you have time take a look on that branch. Thanks.

**Comment by jgrossi** [comment]
I'm gonna close this. This is fixed on version 2, which is going to be release in the next weeks.

**Comment by JeanHules** [comment]
Has this been fixed? I am just curious. I am running 2.3 on 5.3, but cannot figure out how to retrieve the menus and their links. 

I have 
`
namespace App\Models;
use Corcel\Model\Menu as Corcel;
class Menu extends Corcel 
{
    protected $connection = 'wp';
}
`

and method is:

`		
$menu = Menu::slug($name)->first()->items;
print_r($menu);exit;
`

as my model, but I am not getting any useful data. I see the post_type => nav_menu_item, but the title is empty. It's like it is not linked to the page in the nav at all. Any idea what I am doing wrong?

**Comment by jgrossi** [comment]
@JeanHules hi! did you read the docs or my last comment in this thread? `$menu->items` is a collection of `nav_menu_item` posts, but they have nothing in title. That's how it works, the database works. You have to call `->instance()` to get the correct item instance (`Post`, `Page`, `Taxonomy` or `CustomLink`).

**Comment by JeanHules** [comment]
Ok. I figured out the issue. I was using an older version of this code. 

One more brain buster.. I am having issue retrieving the parent nav items. Can you explain how I would do this?

My Code:

```
$menu = Menu::slug($name)->first()->items;
foreach ($menu as $i => $item) {
      $parent = $item->instance()->parent();
      $slug = $item->instance()->slug;
}
```

This does not work.

**Comment by OwenMelbz** [comment]
@jgrossi although you get the "Post" or what ever back - how would you build a menu from it? as far as I can tell it doesn't actually give you what the wordpress menu builder was designed for? e.g I imagine the point of the menu builder was to provide you the information like opening in new window, what the url to go to is, if its a custom url etc?

Have you got any vanilla PHP examples of how to achieve this using the latest Corcel?

**Comment by haghanihakimi** [comment]
This works perfect for me! But how about if I add Product Categories to ```main_menu``` instead of adding pages?
When I add list of pages to main_menu and I use ```->instance()``` I get some instances but when I remove list of pages and I add **Product Categories** and then I use ```->instance()```, I get nothing!
Anyone has any idea how to get list of Product Categories using ```Menu::slug('main_menu')->first();```?

**Comment by haghanihakimi** [comment]
This works! But how about if I add Product Categories to `main_menu` instead of adding pages?

I use version 6.0. of Corcel in a Laravel 9 project and I'm trying to get product categories I added to menu.

When I add list of pages to `main_menu` and I use `instance()` method I get some instances but when I remove list of pages and I add Product Categories and then I use `instance()` method, I get nothing!

As I read [this part of documentation](https://github.com/corcel/corcel#-menu) I expect `instance()` method to return product categories that I added to menu, but I get nothing actually! In this section you mentioned `instance()` method returns Term instance for category menu item. I'm not sure if this means "**product categories**" in menu or something else but at this moment `instance()` method returns null!

Also, for [Multi-levels menus](https://github.com/corcel/corcel#multi-levels-menus) I'm a little confused with documentation. 
First, I tried `$parent = MenuItem::parent();` exactly the way I see in documentation and it returns error `Non-static method Corcel\Model\MenuItem::parent() cannot be called statically`.
I also used this exact example I see in documentation: 
```
$items = Menu::slug('main_menu')->first()->items;
$parent = $items->first()->parent();
```
but I see no output.

How this exactly works? can anyone explain and help me with these two problems please.
