### ISSUE TITLE
Acf and advance query

### ISSUE THREAD

**Issue by dimahali** [corcel/corcel#204]
I am trying to implement corcel in laravel 5.2 app

it is working for simple queries... i am using ACF and trying to convert following query into Corcel

`get_posts( [
                                    'post_type'      => 'news',
                                    'posts_per_page' => 5,
                                    'order'          => 'DESC',
                                    'orderby'        => 'post_date',
                                    'meta_query'    => array(
                                            'relation'      => 'AND',
                                            array(
                                                'key'       => 'news_show',
                                                'value'     => '1',
                                                'compare'   => '=',
                                            ),
                                            array(
                                                'key'       => 'news_landmark',
                                                'value'     => '1',
                                                'compare'   => '=',
                                            ),
                                        ),
                                    ]);`
in corcel something like this
`App\News::status('publish')
                                            ->where('news_landmark', 0)
                                            ->where('news_show', 1)
                                            ->take(5)->get();`

but i am getting column not found error for both columns news_landmark and news_show

another issue is i am trying to get image which is also showing null

in traditional style i am doing something like this
`$img = get_field('slider_image', $slider->ID);`

but when i try $slider->slider_image assuming slider as the variable i am getting null i have tryed meta and fields as well but both do not work

**Comment by jgrossi** [comment]
Hey! Actually `news_show` and `news_landmark` are custom fields, they're part of the `wp_posts

**Comment by jgrossi** [comment]
Hey! Actually `news_show` and `news_landmark` are custom fields, they're part of the `wp_posts` table. To filter `posts` using custom fields you should use something like this:

```php
$posts = Post::whereHas('meta', function ($query) {
    $query->where('meta_key', 'foo')->where('meta_value', 'bar');
})->get();
```

Maybe it's a nice new feature to be implemented in Corcel in a easier way ;-)

**Comment by dimahali** [comment]
Will check this... and what about image issue i am not getting image????

**Comment by jgrossi** [comment]
Hi @dimahali `$img = get_field('slider_image', $slider->ID);` you're just getting a `slider_image` custom field from ACF, but you can do this in Corcel with `$post->meta->slider_image`. Remember, you don't have access to WordPress functions inside Corcel. Cheers, JG.

**Comment by dimahali** [comment]
well i am doing get_filed because i have developed custom functions and initialize wordpress so get_field is working fine but now i want to convert it to Corcel syntax and i have tried $post->slider_image, $post->meta->slider_image and $post->fields->slider_image all are returning null.....

**Comment by dimahali** [comment]
for menu

`use Corcel\Menu;

class WpMenu extends Menu
{
    protected $connection = 'wordpress';
}`

App\Menu::slug('top_menu_eng')->first();

i am getting this error

`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'kiu_portal.term_taxonomy' doesn't exist (SQL: select * from `term_taxonomy` where `taxonomy` = nav_menu and exists (select * from `terms` where `term_taxonomy`.`term_id` = `terms`.`term_id` and `slug` = top_menu_eng) limit 1)`

**Comment by jgrossi** [comment]
@dimahali I could not see the issue here. You're using a bunch of custom functions and I cannot see where are you using Corcel and where it's broken. Can you send me the content of `get_field()` function you've implemented? JG

**Comment by jgrossi** [comment]
@dimahali did you fix this issue?

**Comment by dimahali** [comment]
hey jgrossi sorry for late response... i am a bit busy and not used corcel yet....  saw your upgrade and will look at it as soon as possible... thanks for good work....

**Comment by jgrossi** [comment]
@dimahali no problem :-) any question just open this issue again. JG
