### ISSUE TITLE
Post content missing formatting

### ISSUE THREAD

**Issue by chrisgherbert** [corcel/corcel#205]
When I call $post->post_content or $post->content, the content doesn't include paragraph breaks ad other "implied" formatting that you usually get with WordPress - it just spits out the content directly from the database.

Do we need to reimplement apply_filters('the_content', $content)?  If so, are there any ideas for how to start for doing that?

**Comment by jgrossi** [comment]
Hi @chrisgherbert. Corcel does not support WordPress filters. 

As you said it just grab the data from the database, without including paragraphs, etc. Maybe this can be added as a new feature, reimplementing the WP formatting way into `Post.php`, something like `getContentFormattedAttribuet()`, or anything else. 

Do want to send the PR or can I do that by myself? 

Cheers, JG.

**Comment by sarog** [comment]
Try the following in your Blade templates to treat newlines as HTML breaks (`<br>`) to restore most of the formatting:

`{!! html_entity_decode(nl2br(e($post->content))) !!}`

**Comment by goodbytes-gb** [comment]
It's quite easy to roll your own.

In Laravel I created `App/Helpers/WordPress`

With this: https://gist.github.com/goodbytes-gb/3748c0b43420d2f17eae99ac8c13a811
It is essentially a simplified version of what WordPress does when it outputs the_content tweaked slightly to play nicely with Laravel.

Then in the Post model you can do

```
    public function getFormattedContentAttribute()
    {
        if ($this->content) {
            return WordPress::wpautop($this->content);
        }
        ....
```

Finally in view: `{!! $post->formatted_content !!}`

**Comment by jgrossi** [comment]
@goodbytes-gb do you want to send a PR?

**Comment by goodbytes-gb** [comment]
@jgrossi yes will do some point today.

**Comment by tlaverdure** [comment]
This would be great.

**Comment by goodbytes-gb** [comment]
Finally completed the pull request

#254 

Simply use `$post->formatted_content` instead of `$post->content`

**Comment by jgrossi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Format post content like wpautop function](https://trello.com/c/i6mK9hgm/36-format-post-content-like-wpautop-function)
