### ISSUE TITLE
ACF Pro data retrieval 

### ISSUE THREAD

**Issue by dimahali** [corcel/corcel#210]
Hey J,
 I am using acf and facing dificulty while retriving repeater data and other images.... i am getting an id insted of data when i do something like this

$page->meta->repeater

need help on this

when i dump page data is there but no idea how to loop through

you have done a great job....

thanks in advance...

**Comment by jgrossi** [comment]
Hi @dimahali! Thanks for the message. Corcel supports custom fields even using ACF, but not the complex one like repeater, I think. Check in your `wp_postmeta` table what it's storing for your custom field and we will see what we can do to support it ASAP. Cheers. JG

**Comment by jgrossi** [comment]
@dimahali I think `get_field()` function (from ACF) does all the trick to return array with all the repeater data, so this is not implemented in Corcel yet, but it's a really good feature. JG

**Comment by dimahali** [comment]
thanks for the response though a bit ate :-), I have reverted changes to my project because of your late reply and now relying on my own custom functions... ya get_field and get_sub_field are doing the trick.... right now i am a bit busy so will look at this on Sunday.... saw your post on medium and a comment from Eric Arrington having same issue but was not able to reach him... great job by the way... would love to see advance acf implementation....

thanks....

**Comment by jgrossi** [comment]
@dimahali nice! I'm gonna let this issue opened to remember to implement that. Cheers, JG.

**Comment by jgrossi** [comment]
@dimahali just to let you know, I'm working on a new feature that will allow Corcel to retrieve all ACF fields. I'm gonna post news next week I think. JG

**Comment by dimahali** [comment]
Thanks man... this is a good news indeed..... looking forward for an exciting feature....

**Comment by gildebrand** [comment]
@jgrossi first off, thank you very much for creating such a wonderful package for interacting with WordPress! I'm looking forward to using it in more of our future projects, and hope to be able to contribute to the project as well!

I am currently using Corcel for a WP-site where we use the grid editor. I ran into the issue that Corcel doesn't return all data needed to be able to print the grid. I had a look in the WP-database and I guess I could tap the data manually. However, I wonder how far the implementation of ACF Pro fields has come, so I know if I should spend time implementing an own solution or if I should wait a couple of more days 😄 

Best regards!

**Comment by jgrossi** [comment]
Hi @gildebrand thanks! The Corcel plugin for ACF is current under development, but we already launched a release with some fields, take a look http://github.com/corcel/acf. Everything is working well, except "Repeater", that is working in some cases, but I have to write more tests for it and "Flexible Content" that should be implemented soon. JG

**Comment by jgrossi** [comment]
@gildebrand the ACF plugin is on http://github.com/corcel/acf. I'm closing this issue and any needs just let me know. JG
