### ISSUE TITLE
Custom post type relation to Eloquent Model through PostMeta value

### ISSUE THREAD

**Issue by Bartjuh4** [corcel/corcel#211]
How to deal with this? I have a custom post type that is connected to some Eloquent model. The reference to this eloquent model is saved in the post_meta table.

If i only use eloquent models i normally use the belongsToMany or HasManyThrough method but in this example i do not know.

**Comment by jgrossi** [comment]
Hi @Bartjuh4 Corcel uses Eloquent, so a `Corcel\Post` object is an Eloquent model. If you have to include some relationship just extends the `Corcel\Post` class with your own and include the relationships you need :-)

```php
namespace App\Corcel;

class Post extends \Corcel\Post
{
    protected $connection = 'wordpress';

    public function something()
    {
        return $this->hasMany(App\AnotherModel::class, 'field_id');
    }
}

$post = App\Corcel\Post::find(1); // using your Post class
echo $post->something->some_property;
```

Anything just ask. Cheers, JG.

**Comment by jgrossi** [comment]
@Bartjuh4 did you fix that? I'm gonna close this issue. Any question just let me know. JG

**Comment by noplanman** [comment]
Sorry for reviving this old issue, but I have the exact same problem.
I have a post with a meta value of another post type ID.

```
# posts
ID	post_type
1	post
2	channel_cpt

# postmeta
meta_id	post_id	meta_key	meta_value	
210	1	channel_cpt	2
```

I'd like something like `Post::find(1)->channelCpt` to give me the post with ID 2, but I get `null`.

How can I achieve this?
