### ISSUE TITLE
name of the images

### ISSUE THREAD

**Issue by webeswork** [corcel/corcel#212]
How can I get the images name of the post? 

$post = \App\Post::find(148);

//I tried this but I didn't get them.
   echo $post->thumbnail;
   echo $post->image;

Thank you!

Zsolt

**Comment by jgrossi** [comment]
Hi @webeswork are you sure you have an image attached with this Post 148?

```php
$post = Post::find(148);
$post->thumbnail->attachment; // this gives you an instance of `Corcel\Attachment` object
$post->image; // this gives you the image URL (string)
```

If you're getting `NULL` that's because your post doesn't have any attachment related with it. 

Anything just ask. JG

**Comment by jgrossi** [comment]
@webeswork did you fix that?
