### ISSUE TITLE
Problem with Auth

### ISSUE THREAD

**Issue by lordmilutin** [corcel/corcel#214]
I was trying to replace Laravel default login logic to use Wordpress data to login with this package.

I did add service provider i config/app.php.
But it was not working, have no idea why, credentials were okay,

My User model:

```
namespace App\Models;

use Illuminate\Notifications\Notifiable;

class User extends \Corcel\User { 
    use Notifiable;

    protected $connection = 'wordpress'; 

    ...
}
```

My `config/auth.php`

```
'providers' => [
        'users' => [
            'driver' => 'corcel',
            'model' => \App\Models\User::class,
        ],
```

And basic Laravel auth method was not working nor the Manually auth users with attempt method.

```
if (Auth::attempt(['user_login' => $username, 'password' => $password])) {
            // Authentication passed...
}
```

I had to make workaround like this:

```
$userProvider = new \Corcel\Providers\AuthUserProvider(["model" => User::class]);

$user = $userProvider->retrieveByCredentials(['username' => 'admin']);

if(!is_null($user) && $userProvider->validateCredentials($user, ['password' => 'password'])) {
    // successfully login
   var_dump("SUCCESS");
}
var_dump("ERROR");
```

Now I get success as report, but I can't access a user with: `auth()->user()`

So, how can I make this working? Did I miss something?

**Comment by bgallagh3r** [comment]
I agree.  Further clarification on how to use Corcel Auth with the WP credentials to log in would be very helpful.

**Comment by rundef** [comment]
Hi,

Did you correctly register **Corcel\Providers\Laravel\AuthServiceProvider** as a service provider - and not **Corcel\Providers\AuthServiceProvider** ?

Which version of Laravel are you using ?

**Comment by lordmilutin** [comment]
I am using Laravel 5.3
And I have added
`Corcel\Providers\Laravel\AuthServiceProvider::class,`

**Comment by rundef** [comment]
If you are using the **AuthenticatesUsers** trait for your LoginController, Laravel is expecting a field named **email** to contain the username ...
But you can override the [username() function](https://github.com/laravel/framework/blob/fca954dd807e93d8e734c36357b9ee46617f77b0/src/Illuminate/Foundation/Auth/AuthenticatesUsers.php#L128) in your controller to specify another field name

**Comment by jgrossi** [comment]
@lordmilutin did you fix your problem? any help?

**Comment by lordmilutin** [comment]
I didn't really fix it but it works somehow.

Basic Laravel auth is not working, but I didn't really need it. I am building API only, so when I added JTW library for auth, it worked fine with this package.

**Comment by jgrossi** [comment]
@lordmilutin Hm ok! We have to fix some issues with Laravel auth. I'm gonna close this issue and anything you need just let us know. JG

**Comment by ulshamim** [comment]
@lordmilutin How did you add jwt library. I am using https://github.com/tymondesigns/jwt-auth package and added 
```
 public function authenticate(Request $request)
    {
  
        $credentials['user_login'] = $request->get('user_login');
       echo $credentials['user_pass'] = md5($request->get('user_pass'));
        try {
            if (! $token = JWTAuth::attempt($credentials)) {
                return response()->json(['error' => 'invalid_credentials'], 401);
            }
        } catch (JWTException $e) {
            return response()->json(['error' => 'could_not_create_token'], 500);
        }

        return response()->json(compact('token'));
    }
```
   
code in LoginController.php but it gives me **invalid_credentials** error. I have double check the credentials and it's working fine in wordpress login. 

Can you please help me with this topic?

**Comment by lordmilutin** [comment]
@ulshamim 
Was long time ago, but you need to set first inside of
`config/jwt.php` - `'user' => \Corcel\User::class,`

And also same inside of `config/auth.php`

Then you can do this
```
$userProvider = new \Corcel\Providers\AuthUserProvider(["model" => User::class]);

$user = $userProvider->retrieveByCredentials(['username' => 'admin']);

if(!is_null($user) && $userProvider->validateCredentials($user, ['password' => 'password'])) {
    // successfully login
   var_dump("SUCCESS");
}
var_dump("ERROR");
```

**Comment by pesakitan22** [comment]
@lordmilutin how do you authenticate using jwt?
