### ISSUE TITLE
Visual Composer compatibility

### ISSUE THREAD

**Issue by Raminsadeghi** [corcel/corcel#215]
I have a page created by visual composer, Any idea how can I convert it's shortcodes when I retrieve page content by your package?

**Comment by jgrossi** [comment]
@Raminsadeghi `visual composer` you mean the `page builder` plugin?

**Comment by Raminsadeghi** [comment]
yes, it creates page content with shortcodes. When I retreive data from page or posts with your package, it just some shortcodes, and I must delete those shortcodes. I think it's awesome to has a support on visual composer plugin.

**Comment by marlongichie** [comment]
@Raminsadeghi @jgrossi did you ever come up with any ideas on how to make this work?

**Comment by jgrossi** [comment]
@Raminsadeghi did you fix that? did you try to user the Corcel shortcode feature?

**Comment by KodeStar** [comment]
It's a shame corcel doesn't work with visual composer, would make things a lot easier, client can make their changes in visual composer and corcel display it on the front end.

As far as I can tell Corcels shortcode feature wont work because all it does is allow you to replace a shortcode with something else, which would mean having to understand what every shortcode in visual composer does and replicate the functionality.

**Comment by p-drolima** [comment]
F sick of hearing about visual composer! Its probably one of the worst plugins from a developer point of view

**Comment by KodeStar** [comment]
I don't disagree, unfortunately with a wordpress backend, most clients want the ability to use visual composer, the best option is to not use wordpress at all.

**Comment by p-drolima** [comment]
yes, but clients are looking for cost effective solutions, so kind of needs to be used. the thing is that WP could actually do much better in integrating some functionality so we dont need to resort to this type of plugin

**Comment by jgrossi** [comment]
@KodeStar @p-drolima it would be awesome to have a `corcel/visual-composer` plugin ;-)

**Comment by jgrossi** [comment]
@KodeStar once you have experience with that we could start this project together. what do you think?
