### ISSUE TITLE
Cannot install Corcel with Laravel 5.1.*

### ISSUE THREAD

**Issue by saimiris** [corcel/corcel#225]
Hi there,

When trying to install Corcel on my Laravel 5.1.* project by typing, I get this error message:

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Conclusion: remove laravel/framework v5.1.45
>     - Conclusion: don't install laravel/framework v5.1.45
>     - jgrossi/corcel v1.3.0 requires illuminate/database ~5.3.0 -> satisfiable by illuminate/database[v5.3.0, v5.3.16, v5.3.23, v5.3.4].
>     - jgrossi/corcel v1.3.1 requires illuminate/database ~5.3.0 -> satisfiable by illuminate/database[v5.3.0, v5.3.16, v5.3.23, v5.3.4].
>     - jgrossi/corcel v1.3.2 requires illuminate/database ~5.3.0 -> satisfiable by illuminate/database[v5.3.0, v5.3.16, v5.3.23, v5.3.4].
>     - jgrossi/corcel v1.3.3 requires illuminate/database ~5.3.0 -> satisfiable by illuminate/database[v5.3.0, v5.3.16, v5.3.23, v5.3.4].
>     - don't install illuminate/database v5.3.0|don't install laravel/framework v5.1.45
>     - don't install illuminate/database v5.3.16|don't install laravel/framework v5.1.45
>     - don't install illuminate/database v5.3.23|don't install laravel/framework v5.1.45
>     - don't install illuminate/database v5.3.4|don't install laravel/framework v5.1.45
>     - Installation request for laravel/framework == 5.1.45.0 -> satisfiable by laravel/framework[v5.1.45].
>     - Installation request for jgrossi/corcel ^1.3 -> satisfiable by jgrossi/corcel[v1.3.0, v1.3.1, v1.3.2, v1.3.3].
> 
> 
> Installation failed, reverting ./composer.json to its original content.

What can I do to solve this issue?

Thanks!

**Comment by jgrossi** [comment]
@saimiris The last version of Corcel supports only Laravel 5.3 but you can install a previous version that supports Laravel 5.1 `v1.1.5`. I have plans until the next week to make the current version of Corcel working in Laravel 5.0+, but this is not possible for now. JG

**Comment by saimiris** [comment]
Hi there,

Many thanks for your very fast answer. 

1) What is the Corcel version number I should install then?

2) Can you please update me when the latest Corcel version will work with Laravel 5.1.*?

**Comment by jgrossi** [comment]
@saimiris 

1) `v1.1.5`
2) Sure!

JG

**Comment by saimiris** [comment]
Many thanks. It works fine!

**Comment by jgrossi** [comment]
Great! Anyway ASAP I'm gonna make the current version `5.0+` compatible. JG
