### ISSUE TITLE
How to retrieve custom post type from Toolset ?

### ISSUE THREAD

**Issue by wimnok** [corcel/corcel#227]
Related to another question on this topic, I can see the meta information coming from Toolset custom fields, e.g wpcf-customfield (on custom post types), but the method

- $post->wpcf-customfield or
- $post->meta->wpcf-customfield
does not render the content.
(so, with a var_dump from the $post object, I can see the actual content... but the methods can not get the values..)

Any ideas how to solve this ?

**Comment by jgrossi** [comment]
@wimnok Hey! Thanks for the topic. When you said `Toolset` you mean Toolset from WP-Types https://wp-types.com/? Actually I don't know how they store custom fields in the database. If it stores like WordPress just get the field like `$post->meta->field_name` but if it stores in a different way maybe we can create a plugin to it like the `corcel/acf`. JG

**Comment by wimnok** [comment]
thanks for your comment; it's indeed the WP-Types module. We use it pretty heavily in a number of sites.
I will dig into it further. In any case, the required fields show up when dumping the result from a call using your module...

**Comment by wimnok** [comment]
Do you have any suggestions how to start adjusting the code, or have some kind of plugin like corcel/acf ?
