### ISSUE TITLE
How can I set the default connection to wordpress? Getting DB error trying for ACF fields.

### ISSUE THREAD

**Issue by redroses** [corcel/corcel#228]
Junior:
I have 2 database connections: default and wordpress.
I extend the Corcel models.
namespace App\Extensions\Corcel\Models;
use Corcel\Post as CorcelPost;

class Post extends CorcelPost {
protected $connection = 'wordpress';
.....
}
Everything works fine.

However, I am now trying to get ACF fields.
$post->acf->seo_description

I get the following error:
Table 'smk.postmeta' doesn't exist (SQL: select * from `postmeta` where `post_id` = 39 and `meta_key` = _seo_description limit 1)

This is because PostMeta is using the default connection.

Couple questions:
1) Is there an easy way to set the connection to wordpress for all Corcel models. Corcel\Post, Corcel\PostMeta.

Also Post and PostMeta reference the Corcel Models.
public function meta()
    {
        return $this->hasMany('Corcel\PostMeta', 'post_id');
    }

2) How does this impact the models I extend?

Thanks for any feedback.

**Comment by redroses** [comment]
Works fine.
Changed $post->acf->seo_description
To $post->meta->seo_description

Not sure when I need to use acf then.
The ACF wordpress plugin is storing the data in the wp_postmeta table and $post->meta->seo_description gets the data fine.

**Comment by jgrossi** [comment]
Hey @redroses! Thanks for the message. Actually the `corcel/acf` plugin has some issues about the connection, you're right. If the field you want to get the value is a simple one like text, number, etc, go ahead and use `$post->meta->field_name`. The ACF plugin is more interesting for multiple fields, like select one, checkbox, repeater, etc, which there's a logic to filter the results, instead just getting it from the DB. JG

**Comment by redroses** [comment]
Ok. Thanks for the reply.
I'll give corcel/acf a look when I need more acf functionality.
