### ISSUE TITLE
Custom db prefix per table

### ISSUE THREAD

**Issue by lsfiege** [corcel/corcel#229]
It's possible to handle a different db prefix for user and usermeta tables?, eg: foo_post, foo_postmeta and bar_user, bar_usermeta.

Great component! Greetings

**Comment by jgrossi** [comment]
Hi @lsfiege! You mean just for `user` and `usermeta` tables? You can extend the `User` class setting your own `$connection` attribute to the db connection you want. Is this enough?

**Comment by lsfiege** [comment]
Hi @jgrossi! I'm using laravel and have tried to do that, but isn't worked for me. I have seen the code of your component and noticed that you handle a `$table` attribute (in each class), which does not implement the prefix since it delegates it to other Illuminate classes (`Model` and `Capsule`). I guess it's a very particular case.
Greetings!

**Comment by jgrossi** [comment]
@lsfiege it does implement the table prefix, but this is not set in the `$table` attribute, but in the `preffix` config in the database connections. This is not a particularity of Corcel, but this is how Laravel works. You should not include `wp_` in the `$table` attribute, but include it in another database connection. JG
