### ISSUE TITLE
How to get posts not in one category?

### ISSUE THREAD

**Issue by amjithps** [corcel/corcel#231]
Hi,

I am just curious to know how to select all posts not in one category.

`$posts = BlogPost::taxonomy('category', 'mycat')->type('post')->published()->get();`

will give posts in _mycat_ but i would like to know how we get posts not in _mycat_

Thanks in advance

**Comment by josec89** [comment]
I think that's easy to do in Laravel's queries (Eloquent) isn't it?

try this:

``` 
$posts = BlogPost::taxonomy('category', '<>', 'mycat')->type('post')->published()->get();

```

**Comment by amjithps** [comment]
It didnt work. 

I see taxonomy method accepts only taxonomy and term

`public function taxonomy($taxonomy, $term)`

**Comment by josec89** [comment]
Uh, where is that method? cannot see it. I suggest eloquent complex query using `whereHas`

```
$posts = BlogPost::whereHas('taxonomies', function($q) {
    $q->where('taxonomy', 'category')
         ->whereHas('term', function($q) {
             $q->where('slug', '<>', 'mycat');
         });
})->type('post')->published->get();
```

Makes sense? Don't know if the code will work as is but might give you an idea of how to implement :)

**Comment by jgrossi** [comment]
@josec89 that method is in `PostBuilder` class ;-)
@amjithps this method works only for querying post with that term, not the opposite. I suggest you to do what @josec89 suggested, using Eloquent only way :-)
