### ISSUE TITLE
wanting to use different db prefix for laravel tables and wp tables

### ISSUE THREAD

**Issue by Jossnaz** [corcel/corcel#233]
i want to create my tables like this

```
lar_campaign
lar_campaign_tag
```
etc

thing is when i change `database.php` 

```
        'mysql' => [
            'driver' => 'mysql',
...
            'prefix' => 'wp_',
        ],

```

too

```
        'mysql' => [
            'driver' => 'mysql',
...
            'prefix' => 'lar_',
        ],

```

and open the page

it explodes with

```

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'user_registered' in 'order clause' (SQL: select * from `lar_users` order by `user_registered` desc)

```

am i missing something?

so i guess now laravel looks up the table with prefix `lar_` instead of going to the `wp_users` tables...

**Comment by jgrossi** [comment]
Hi @Jossnaz what's WordPress are you talking about?

**Comment by Jossnaz** [comment]
@jgrossi wordpress 4.7

basically i had to change all prefixes to `wp_` to make things work. Which make it a bit hard to see what table is from wordpress and what tables i have created myself. 

```


        'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix' => 'wp_',
            'strict' => true,
            'engine' => null,
        ],

        'wordpress' => [ // this is your Corcel database connection, where WordPress tables are
          'driver'    => 'mysql',
          'host' => env('DB_HOST', '127.0.0.1'),
          'port' => env('DB_PORT', '3306'),
          'database' => env('DB_DATABASE', 'forge'),
          'username' => env('DB_USERNAME', 'forge'),
          'password' => env('DB_PASSWORD', ''),
          'charset'   => 'utf8',
          'collation' => 'utf8_unicode_ci',
          'prefix'    => 'wp_',
          'strict'    => false,
          'engine'    => null,
        ],


```


if i use `lar_` in the mysql definition, it seems to mix up the table prefixes

**Comment by jgrossi** [comment]
@Jossnaz you have to include the WP prefix just for the connection where your WordPress install is, in this case `wordpress`. You don't have to use WP prefix in `mysql` connection, once that connection is for your apps table, not WP ones.

Extend the `Corcel\Post` class creating your own `App\Post` class and set the `$connection = 'wordpress';`. Then call `App\Post::find(1)->post_title`. This way your Post class will use the `wordpress` connection and your `mysql` one will be intact. JG

**Comment by Jossnaz** [comment]
@jgrossi that's exactly what I did and had in place

my post definition is like this:


```


namespace Caup\Models;

use Corcel\Post as Corcel;

class Post extends Corcel
{
  protected $connection = 'wordpress';
}


```


the thing is, it is not about `Post` but about `User`

my user definition is 


```

namespace Caup;



class User extends \Corcel\User
{

}


```


so i guess I have to use a 

`  protected $connection = 'wordpress';` in the user class as well?

**Comment by jgrossi** [comment]
@Jossnaz yep, because Corcel comes with the `default` connection name. I'm working in a general fix for that, maybe I'll have something tomorrow morning. This should fix this general connection issue in Laravel. JG

**Comment by Jossnaz** [comment]
@jgrossi it really isn't an issue, i just didnt know. If you add it to the readme in a good location i wouldn't have stumbled over it. I guess a more experienced laravel developer would have figured it out himself, but i have never used that field before (`$connection`)

**Comment by jgrossi** [comment]
Yep, it should be fixed soon 👍

**Comment by Jossnaz** [comment]
@jgrossi now i am confused again. So your idea with the authentication etc is to use laravel user table, or to use the wordpress user table?

**Comment by Jossnaz** [comment]
@jgrossi we discussed an issue here: https://github.com/corcel/corcel/issues/232 that is under the assumption that for authentication the wordpress tables are used, right?

**Comment by jgrossi** [comment]
@Jossnaz it's for the WordPress `wp_users` table. It's about logging a WP user inside a Laravel app. JG

**Comment by Jossnaz** [comment]
but the tables are not supposed to exist next to each other? e.g. only
wp_users no laravel users table

**Comment by jgrossi** [comment]
That's why we used to use different database connections, for example `mysql` for app (Laravel) tables and `wordpress` or even `corcel` for WordPress tables. JG

**Comment by jgrossi** [comment]
@Jossnaz in Corcel 1.4.1+ you can just have a `wordpress` or `corcel` connection and Corcel will use that for all models. And now Corcel is compatible starting from Laravel 5.1 to 5.4 ;-) anything just let me know. JG

**Comment by Jossnaz** [comment]
That was exactly the problem! The wp_users table with users model uses
which connection? It should use wordpress but it did use laravel connection
and there is no lar_users

**Comment by jgrossi** [comment]
@Jossnaz are you using different connections, right? one for Laravel stuff and another one for Corcel, right? did you tried that using the last Corcel version?

**Comment by ninthspace** [comment]
I had the same issue as @Jossnaz when developing a non-Laravel app that just happens to use Capsule, in that the Corcel setup clobbers any previous Capsule setup. Corcel\Database::connect doesn't have a name parameter so addConnection() always overrides default.

I resolved this by just chaining the Corcel connection to Capsule via its addConnection() method, which allowed me to specify the connection name, and then using inside my Post class etc.

**Comment by jgrossi** [comment]
@ninthspace the `Database::connect()` is only a simpler way to add Capsule. You can add Capsule by hand and Corcel will work the same way.

BTW `Database::connect()` returns the `Capsule` instance, then you can add others connections if necessary, but you can just add Capsule in your bootstrap file for example:

```php
$capsule = new Capsule();
$capsule->addConnection($params, 'my_connection_name');
$capsule->bootEloquent();
```
