### ISSUE TITLE
Corcel use Laravel DB default connection

### ISSUE THREAD

**Issue by niko-afv** [corcel/corcel#236]
Hi, i have try use Corcel in my Laravel 5.3 project and throw this error:

`Base table or view not found`

with query:

`select * from postmeta where post_id = 7 and meta_key = banners limit 1`

Corcel doesn't use my wordpress connection, but use my laravel default connection.

This problem isn't revolve it yet?

@jgrossi , Can you help me with that?

Thanks!

**Comment by jgrossi** [comment]
Hey @niko-afv thanks for using Corcel. Actually I'm working on the v2 of Corcel and it'll be much more compatible with Laravel than now.

I'm gonna make some changes in the current version to make sure it works well with your connection in Laravel, but for now you can just extend the `Post` class and it'll use the new connection like this:

```php
namespace App\Post;

class Post extends \Corcel\Post
{
    protected $connection = 'my_connection';
}
```
Hope it helps, JG

**Comment by jgrossi** [comment]
Hm and then use your classe like `App\Post::find(1)->meta` ;-)

**Comment by niko-afv** [comment]
Hi @jgrossi ! 

Thanks for the quick response!

I already did what you said. I added the $connection property to my Post model.
Actually, the problem comes with the acf plugin. 

When i try something like `$post->acf->url`, Laravel throws an exception because the plugin use the laravel's default connection. How can i force acf plugin to use wordpress' conn?

**Comment by jgrossi** [comment]
@niko-afv I'm gonna commit a quick change I think will fix that. Just a second.

**Comment by niko-afv** [comment]
Thanks @jgrossi,

I will waiting for!

**Comment by jgrossi** [comment]
@niko-afv please update your `composer.json` to install another `corcel/acf` version: `dev-bugfix/db-connection`. It should look like this:
```
"corcel/acf": "dev-bugfix/db-connection",
```
Let me know any issue, please. JG

**Comment by jgrossi** [comment]
@niko-afv I did a quick test and it seems to be working. I'm gonna tag that, so just update your composer. It's now version `0.1.3`. Let me know about any issue. JG

**Comment by niko-afv** [comment]
@jgrossi  it works.

Thanks!
