### ISSUE TITLE
Taxonomy class not using Corcel namespace, or WPDB connection.

### ISSUE THREAD

**Issue by MadMikeyB** [corcel/corcel#237]
The Taxonomy class is not using the Corcel namespace. 

You need to add a `use \Taxonomy` at the top of the file if it is being used (undocumented) and it uses the database connection from the .env file, not from the wordpress connection set in `config/database.php`. 

Meaning it scans the Laravel database for term_taxonomy, not the WordPress one.

If this is not desired intended behaviour, I can attempt a PR to fix this.

**Comment by jgrossi** [comment]
@MadMikeyB now Corcel looks for a `wordpress` or `corcel` database connection. This is from version `v1.4.1`. can you give another try?
