### ISSUE TITLE
Optmimize database queries

### ISSUE THREAD

**Issue by niko-afv** [corcel/corcel#238]
Hi, I want to mention you about a point that I noticed when using Corcel that has served me a lot and I thank you for the work done.

When this line is executed: 

`$banners = WpPage::type('page')->slug('home')->first()->acf->repeater('banners');`
(WpPage extends from Corcel\Post)

debug bar show me 116 queries  and just there 3 acf elements to take [see image](http://www.awesomescreenshot.com/image/2077749/087f26c9492b3e77b3b040d2a23e33bb)

Max 5 queries are from the application as such and all the others are from Corcel / Wordpress. Is there any way to optimize the number of queries that are executed? . Maybe consider it for the next version.

Greetings.

**Comment by jgrossi** [comment]
I'm gonna take a look on it 👍

**Comment by marcoboom** [comment]
The problem with the repeater is that each field needs minimal 3 queries per repeater subfield. Every time it repeates, 2 of the 3 queries are identical as the previous in the loop. 

At this point I don't have a nice solution to solve this. For now I try to cache as much as possible.

**Comment by alanhr** [comment]
Why u don't use the join instead of Eloquent queries?

**Comment by jgrossi** [comment]
Hi @alanhr! Thanks for the comment. Do you have any code solution for that using joins like you said? Can you write some code or even send a PR? Thanks!

**Comment by alanhr** [comment]
Hi @jgrossi , in my opinion this implementation doesn't have be done inside of corsel.
Why not? 
Because for me this implementation is a especifique custom of that project.

**Comment by jgrossi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve SQL queries in Repeater and Flexible Content fields](https://trello.com/c/XZxwbBkD/15-improve-sql-queries-in-repeater-and-flexible-content-fields)
