### ISSUE TITLE
Bug - Laravel 5.4

### ISSUE THREAD

**Issue by tlaverdure** [corcel/corcel#242]
Getting this error when trying to use `$this->taxonomies()`

```
Call to undefined method Illuminate\Database\Query\Builder::getBelongsToManyCaller()
```

**Can these lines be omitted?**
https://github.com/corcel/corcel/blob/dev/src/Model.php#L130-L132

Not sure what it's purpose is for, but it appears to work without it

**Comment by jgrossi** [comment]
@tlaverdure I'm gonna take a look on it, thanks for reporting. JG

**Comment by h-collector** [comment]
I got the same error, found that method was renamed:
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php#L298

**Comment by pesakitan22** [comment]
hello, is there a solution yet?

**Comment by jgrossi** [comment]
@h-collector you're right, not L5.4 uses the same connection for parent models, but we cannot required only Laravel 5.4, at least for now. Now it's compatible with L5.3 but the goal is to make it working from Laravel 5.0 to 5.4, without restrictions.

@pesakitan22 not for now

**Comment by jgrossi** [comment]
@tlaverdure @h-collector @pesakitan22 it seems the Corcel version `1.4.1` fixed that. Please update the composer and let me know if it's working. JG

**Comment by tlaverdure** [comment]
Looks great. Thanks!
