### ISSUE TITLE
Model connection empty after update from 1.3.3 to 1.4.0

### ISSUE THREAD

**Issue by ChrisThompsonTLDR** [corcel/corcel#243]
We've been using Corcel 1.3.3 without issue for a while.  Today I updated to 1.4.0.  We have a `mysql` connection for all models except our Post model.  Post uses the `wp` connection.  When dumping the Model, the connection property is empty now and the model attempts to use the default connection, `mysql`.

Commands I ran:
```
svn up
composer update
php artisan config:cache
```

Our Post model
```
<?php

namespace App;

use Corcel\Post as Corcel;

class Post extends Corcel
{
    protected $connection = 'wp';
}
```

Our `wp` connection:
```
        'wp' => [
            'driver' => env('WP_DB_CONNECTION', 'mysql'),
            'host' => env('WP_DB_HOST', 'localhost'),
            'port' => env('WP_DB_PORT', '3306'),
            'database' => env('WP_DB_DATABASE', 'forge'),
            'username' => env('WP_DB_USERNAME', 'forge'),
            'password' => env('WP_DB_PASSWORD', ''),
            'charset' => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix' => env('WP_DB_PREFIX', ''),
            'strict' => true,
            'engine' => null,
        ],
```

Our .env
```
WP_DB_CONNECTION=mysql
WP_DB_HOST=localhost
WP_DB_PORT=3306
WP_DB_DATABASE=wp
WP_DB_USERNAME=wp
WP_DB_PASSWORD="nothanks"
WP_DB_PREFIX="wp_"
```

Reverting to 1.3.3 resolved the issue.

**Comment by jgrossi** [comment]
@ChrisThompsonTLDR hey thanks for reporting this. Actually the `1.4.0` had some breaking tests I'm working on it. If you see how to fix that soon please send a PR. thanks again! JG

**Comment by h-collector** [comment]
In 1.4.0 connection name is overriden
https://github.com/corcel/corcel/blob/v1.4.0/src/Model.php#L204

Also related to #242 , I think there is no need (L5.4) to override Eloquent model now

**Comment by jgrossi** [comment]
@h-collector the problem is not with that only... even removing this new adds the `phpunit` are still not passing

**Comment by jgrossi** [comment]
@ChrisThompsonTLDR @h-collector it seems the Corcel version `1.4.1` fixed this issue. Please, update Corcel, confirm and let me know.  JG
