### ISSUE TITLE
Laravel 4.2

### ISSUE THREAD

**Issue by waydeshepard** [corcel/corcel#245]
I am trying to use this package with laravel 4.2, what version of the package should i use?

**Comment by jgrossi** [comment]
Hi @waydeshepard sorry about the late response. Unfortunately there's no release for Laravel 4.2. I suggest you to fork the corcel repository and change the `composer.json` to Laravel 4.2 packages. It should work well I guess.  JG

**Comment by jgrossi** [comment]
I noticed some time ago that @adrianogl installed Corcel with Laravel 4.2 and it was working well, I guess. Can you help @adrianogl?
