### ISSUE TITLE
calling corcel from within wordpress?

### ISSUE THREAD

**Issue by Jossnaz** [corcel/corcel#246]
it is very easy to access wordpress from laravel. What about the other way?

how can I, say, access Auth::user() from within a wordpress functions.php? is there an easy way to do it?

**Comment by waydeshepard** [comment]
You might wanna look into this worpdress plugin for that: https://wordpress.org/plugins/larapress/

**Comment by jgrossi** [comment]
Hey @Jossnaz sorry about the late response. Did you try to `require` Composer inside your WordPress? Then you can call the Laravel classes using the Composer autoload. JG
