### ISSUE TITLE
Class mapping models

### ISSUE THREAD

**Issue by marcoboom** [corcel/corcel#250]
Hi @jgrossi 

What do you think of making a class map of all models?

For some models I created my own models, like the Page model, that model extends the Corcel\Page model. 

In this model I created some accessors. That works great. But when I get a page from a relation or an ACF field, the page will be an instance of Corcel\Post. From that instance my accessor is not available unfortunately.

My idea is to create a config in the Corcel package, with a mapping of all classes.

```
return [
  'post' => Corcel\Post::class,
  'page'=> App\Page::class,
];
```

In every place where a relationship is defined or model is needed, we check in the class mapping which model has to be used. 

Caveat of this is that you cannot typehinting the Models anymore.

I hope to hear from you.

**Comment by marcoboom** [comment]
I did not notice the feature registerPostType. I think that will do the job.

**Comment by jgrossi** [comment]
Hi @marcoboom sorry about the delay. Those last days were hard :-)
Maybe this can be a great feature. I started a config file with some details like database connection to be used, and this classmap can be awesome. I like it, really. What do you think?

**Comment by jgrossi** [comment]
@marcoboom I'm working on new Corcel versions. The `v2.x.x` version will be compatible with Laravel `5.x.x` versions, for example, Corcel 2.3 with Laravel 5.3 and Corcel 2.4 with Laravel 5.4.

I'm currently rewriting almost everything, refactoring, writing more teste (using now Sqlite `:memory` with factories and migrations). Please take a look on `2.4` branch. Once it's finished I'm gonna start creating and tagging 2.3, 2.2, 2.1 and 2.0.

The reason I'm commenting here is that you suggested a class map, what I'm already doing in a `corce.php` config file in `2.4` branch, but for now for custom post types, avoiding the usage of `registerPostType()` method (you can still use it but from the config file is automatically loaded). 

https://github.com/corcel/corcel/blob/2.4/tests/Unit/Model/PostTypeTest.php#L58

Please take a look and if you have any ideia or contribution let me know or send a PR to `2.4` branch, ok? Thanks!

PS: I'm working in a public Trello board to make sure to cover everything. If you want to join it, be welcome.
