### ISSUE TITLE
Is it possible to get the next or previous post?

### ISSUE THREAD

**Issue by smoothlikejazz** [corcel/corcel#256]
Love corcel by the way!, my wp/laravel integration has been painless.

I was wondering if there was any functionality to retrieve the next and previous post links or even next and previous post information similar to how the below functions from wordpress core work

Function: next_posts_link()
Function: previous_posts_link()

I have a particular post i'm showing, using the below
```
$post = Post::slug($slug)->first();
```

and would like to use
```
$nextPost = $post->nextPost();
```

if not, if you could provide any pointers on how i can implement.

Thanks

**Comment by jgrossi** [comment]
Hi @smoothlikejazz. If you want to know the next/previous post just for pagination you can use the default `->paginate()` method in Laravel. Something like this:

```php
$posts = Post::paginate(10); // 10 posts per page
```
and in the view:
```php
{{ $posts->links() }}
```
This will print all pages links ;-)

Hope helped you. Cheers, JG.

**Comment by smoothlikejazz** [comment]
Hey @jgrossi, 

for now i have modified the extended class

```
<?php

namespace App\WP\Post;

use Corcel\Post as Corcel;

class Post extends Corcel
{
    protected $connection = 'wordpress';

    function get_previous_post( $post_id ) {
        // Get a global post reference since get_adjacent_post() references it
        global $post;

        // Store the existing post object for later so we don't lose it
        $oldGlobal = $post;

        // Get the post object for the specified post and place it in the global variable
        $post = get_post( $post_id );

        // Get the post object for the previous post
        $previous_post = get_previous_post();

        // Reset our global object
        $post = $oldGlobal;

        if ( '' == $previous_post ) {
            return 0;
        }

        return $previous_post;
    }

    function get_next_post( $post_id ) {
        // Get a global post reference since get_adjacent_post() referencfes it
        global $post;

        // Store the existing post object for later so we don't lose it
        $oldGlobal = $post;

        // Get the post object for the specified post and place it in the global variable
        $post = get_post( $post_id );

        // Get the post object for the next post
        $next_post = get_next_post();

        // Reset our global object
        $post = $oldGlobal;

        if ( '' == $next_post ) {
            return 0;
        }

        return $next_post;
    }

}
```

So that i can extract the next and previous posts links, wondering if there is a better way i see that this is using the global wp variable which i'd like to avoid.

**Comment by jgrossi** [comment]
Hi @smoothlikejazz you're doing something wrong. You can two options to use WordPress inside a Laravel app:

1. Include `wp-blog-header.php` inside Laravel and use WP functions like `get_post()`, etc.
2. Using Corcel.

You're using both Corcel and WP functions. So there's a overhead that's not necessary.

To get the next/previous post I suggest you to add a method inside your `Post` class like `fetchNextAndPrevPosts($postId)`, repeat the select and get one post before and one after the current based on the `$postId`:

```php
<?php 

use Corcel\Post as Corcel;

class Post extends Corcel
{
    protected $previousPost = null;
    protected $nextPost = null;

    // Remember here that if you have a `wordpress` or `corcel` connection inside config/database.php you don't have to use this, because Corcel will use one of them as default connection
    protected $connection = 'wordpress';

    public function fetchNextAndPrevPosts($postId)
    {
        // Repeat the query here using Post::.....->get();
        // $previous = get the post before the $postId
        // $next = get the post after the $postId
        $this->previousPost = $previous;
        $this->nextPost = $next;
    }

    public function getPreviousPost()
    {
        return $this->previousPost;
    }

    public function getNextPost()
    {
        return $this->nextPost;
    }
}
```

Hope it helps. Cheers.

**Comment by smoothlikejazz** [comment]
Thanks @jgrossi ,
Ahh I see, I figured I was doing something wrong :), thanks for pointing me in the right direction, this is perfect.

**Comment by jgrossi** [comment]
@smoothlikejazz welcome. I'm gonna close this issue for now but anything you need just open it again. Cheers, JG.
