### ISSUE TITLE
how to use shortcodes?

### ISSUE THREAD

**Issue by Jossnaz** [corcel/corcel#258]
sorry i don't get how to use the shortcodes at all

the provided example seems wrong. Why `echo` stuff out in the boot method?

the linked library does seem to be something orthogonal to what wordpress has and seems rather complex.

This is not about wordpress shortcodes?

Basically I want to create a wordpress shortcode from the laravel context.  E.g. [greetuser]

```
function(){
return 'hi' . Auth::user()->display_name;
}
```

so in a wordpress post, in a wordpress context, i want to be able to add [greetuser]

This is not what this is about is it?

**Comment by Jossnaz** [comment]
to make it more clear: i want the shortcode to be available from within wordpress itself e.g. if you create a page in wordpress and from laravel routes. Now wordpress shortcodes I can get by using `apply_filters('the_content', $p->post_content);`

**Comment by jgrossi** [comment]
Hi @Jossnaz if you want to use shortcodes inside WordPress you should not be using Corcel. Corcel is only when you need to use some WP implementations outside WordPress. To create a shortcode inside WordPress just create it in the WP way. You cannot use `apply_filters` function inside Laravel. JG

**Comment by Jossnaz** [comment]
what is you equivalent of apply_filters? I mean do we have one?

i actually import the wordpress wp-load.php in laravel. So i have access to
all functions from within laravel.

**Comment by Jossnaz** [comment]
just for completeness

this is my bootstrap/autload.php of laravel

this works for wordpress non multi site installations

access to all wordpress functions

including using

wp_head()

wp_footer()

in your templates

so you can let your client do all the stuff and crappy static pages in the
menu

you do the business logic

works well

```

<?php

define('LARAVEL_START', microtime(true));

require __DIR__ .'/../../wp-load.php'; //be sure to adjust to where your
wp-load.php is located

/*
|--------------------------------------------------------------------------
| Register The Composer Auto Loader
|--------------------------------------------------------------------------
|
| Composer provides a convenient, automatically generated class loader
| for our application. We just need to utilize it! We'll require it
| into the script here so that we do not have to worry about the
| loading of any our classes "manually". Feels great to relax.
|
*/

require __DIR__.'/../vendor/autoload.php';

/*
|--------------------------------------------------------------------------
| Include The Compiled Class File
|--------------------------------------------------------------------------
|
| To dramatically increase your application's performance, you may use a
| compiled class file which contains all of the classes commonly used
| by a request. The Artisan "optimize" is used to create this file.
|
*/

$compiledPath = __DIR__.'/cache/compiled.php';

if (file_exists($compiledPath)) {
    require $compiledPath;
}


```

**Comment by jgrossi** [comment]
You're doing this wrong. You have to choose to include WP functions inside your Laravel app **OR** use Corcel.

Corcel does not provide any `apply_filter()` function. If you are using WP inside Laravel just use WP functions and forget Corcel. In this case you should use `new WP_Query()` or `get_posts()` to fetch posts inside WP, not Corcel.

**Comment by Jossnaz** [comment]
You seem to misunderstand.

Wordpress is very old, and I don't like working with it.

Corcel is great, hail corcel.


and they work perfectly fine together, i mean right thats their intent.



Whereever I can I use corcel, where I cannot, I use pure wordpress.

You gave an example yourself-> `apply_filter` what worth is a post content,
if it has not run the filters over it?

another example is wp_head() I want let the client have the freedom of
adding plugins, e.g. say a chat plugin. A popup plugin for newsletters
before the user leaves etc. visual composer...
stuff I cannot be bothered with.

I use corcel mainly for the unified login of wordpress and laravel (even
though I seem to have some small issues with it, e.g. logging in / out of
wordpress / laravel does not always log out of the other platform).


so my use case is basically the client said "I WANT WORDPRESS" and I said
"ok fine, but the app will be written with laravel. Laravel is the master,
and all the crap from wordpress I will somehow integrate into the laravel
templates"

**Comment by rundef** [comment]
You have 2 options:
1. use the `apply_filter()` function
2. [redefine the shortcode handler using corcel](https://github.com/corcel/corcel#shortcodes) (automatically applied when you get `$post->content`)

In your case, it should be something similar to this:
```php
Post::addShortcode('greetuser', function ($shortcode) {
  return 'hi' . Auth::user()->display_name;
});
```

**Comment by Jossnaz** [comment]
@rundef so basically if I want to create a shortcode that lives in both worlds I have to stick with the pure rambo WP style. Which is fine. Just trying to figure out a way to access laravel models from within wordpress. I saw the larapress plugin but it caused me an error

**Comment by jgrossi** [comment]
@Jossnaz is that fixed? can I close this issue?

**Comment by Jossnaz** [comment]
@jgrossi well.. to be honest with you, I think corcel should provide an apply_filters or at least access to filtered post content. I mean apply_filter is _only_ used by me, to get the filtered post content of posts. If you lack this in corcel, you cannot read post contents. Was there a strong reason to not include it?

**Comment by jgrossi** [comment]
@Jossnaz but you can get filter post content using `$post->content` and not `$post->post_content`.

**Comment by PayteR** [comment]
If you want to use all functions from WP in Laravel application, then you should try https://framework.themosis.com/
