### ISSUE TITLE
how to make user login?

### ISSUE THREAD

**Issue by krecebli** [corcel/corcel#259]
Hi. I am using just one default db connection and want to make a user login with `Auth::login($user);`, but it returns `null`, and `Auth::check();` is still `false`. Although, `Auth::check();` is `true` in the same request with login attempt, but in the next one is `false`. So, how can I solve this? Maybe, I should use two connections for this, or anything else?

**Comment by jgrossi** [comment]
Hi @krecebli thanks for the contribution. Are you using our `Corcel\Providers\Laravel\AuthServiceProvider` class?

**Comment by krecebli** [comment]
Thanks for such a helpful package :)

Yes, I am.

```
$user = $userProvider->retrieveByCredentials(['username' => 'admin']);

if(! is_null($user) && $userProvider->validateCredentials($user, ['password' => 'secret'])) {
    Auth::login($user);
}
```
Of course, I registered AuthServiceProvider in `config/app.php`. But `Auth::check();` is `true` only in the same request.

**Comment by rundef** [comment]
You don't need to call `retrieveByCredentials` and `validateCredentials` manually.
You need to set the user provider in `config/auth.php` (see the README).
Then, the Laravel authentication mecanism will automatically use wordpress `wp_users` table.

Your controller should be similar to this:
```php
<?php
namespace App\Http\Controllers\Site\Auth;

use Illuminate\Foundation\Auth\AuthenticatesUsers;

use App\Http\Controllers\Controller;

class LoginController extends Controller
{
    use AuthenticatesUsers;

    protected $loginPath = '/';
    protected $redirectPath = '/';
    protected $redirectAfterLogout = '/';

    public function __construct()
    {
        $this->middleware('guest', ['except' => 'logout']);
    }

    public function username()
    {
        return 'username';
    }
}
```

**Comment by krecebli** [comment]
I have already set the user provider in `config/auth.php`, but probably I misunderstood something and was trying with `retrieveByCredentials` and `validateCredentials`. It works with laravel's regular login, thanks :)
