### ISSUE TITLE
Term meta

### ISSUE THREAD

**Issue by FourStacks** [corcel/corcel#260]
Hi @jgrossi 

First up, huge thanks for putting this package together - been putting it through it's paces on a client project and it's been awesome being able to allow my client to use WP as per their request whilst still building in Laravel.

Once I've got a little breathing room after this project is out the way I'm going to see what there is to contribute on Corcel as I can see it being really useful for other projects too (let me know if there's any areas you would particularly like PRs for).

Anyway, onto my question.  Was just digging around and I can't see any way of retrieving term meta data - is that correct?  I've got things set up to pull Yoast SEO meta data from my corcel models but I can't see a way of doing this so cleanly with term meta data.

Could you let me know if I'm missing something?  If it's a feature that's not currently in Corcel then I'm happy to contribute a PR at some stage over the next couple of months?

**Comment by FourStacks** [comment]
The question above still stands but for those wishing to know how to grab Yoast SEO meta for terms, please see this gist on how I implemented things:

https://gist.github.com/FourStacks/0cdbadd989ad81d2cf49252dfa6410d1

**Comment by jgrossi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement SEO integration with YOAST](https://trello.com/c/9Xa1w2EO/2-implement-seo-integration-with-yoast)
