### ISSUE TITLE
reset password error (including fix here)

### ISSUE THREAD

**Issue by Jossnaz** [corcel/corcel#262]
laravel 5.3.31
the commented out is your file and the next line is what actually seems to work:

ResetsPasswords.php

```


<?php

namespace Corcel\Auth;

use Corcel\Password\PasswordService;
use Auth;

trait ResetsPasswords
{
    /**
     * Reset the given user's password.
     *
     * @param \Illuminate\Contracts\Auth\CanResetPassword $user
     * @param string                                      $password
     */
    protected function resetPassword($user, $password)
    {
        $passwordService = new PasswordService();

        $user->user_pass = $passwordService->makeHash($password);

        $user->save();

//        Auth::guard($this->getGuard())->login($user);
        $this->guard()->login($user); //from resetpasswords of laravel
    }
}

```

**Comment by jgrossi** [comment]
I'm working on new Corcel versions, then the `2.3` will be compatible with Laravel 5.3. I'm gonna let this issue opened to make sure it's working on Laravel 5.3.

**Comment by jgrossi** [comment]
@Jossnaz if you have any PR to send please send it to `2.3` branch ok? it's only related with Laravel 5.3 stuff.

**Comment by joeyj87** [comment]
We are using laravel 5.6 with corcel 2.6, yet the issue above occurs. Using the fix provided above resolves the issue but why isn't this part of the latest corcel and the issue closed?
