### ISSUE TITLE
Using corcel with wordpress

### ISSUE THREAD

**Issue by Jossnaz** [corcel/corcel#263]
I wrote before with you guys about corcel and wordpress right, and people told me I was doing it wrong.

Now what is the original idea in using corcel? a simple example?

**Comment by jgrossi** [comment]
Hi @Jossnaz! The original idea is to use Corcel as a PHP package (composer) inside your Laravel (or any framework) app, not including any WP source code into Laravel bootstrap, for example.

If you include WP inside Laravel you don't need Corcel, once you'll have `WP_Query` and all WP functions, but remember you're adding all WP overhead inside Laravel. If you need more advanced WP features I guess this is the only options, once Corcel is for querying data from a WP database.

Cheers.

**Comment by Jossnaz** [comment]
so can you give me an example of a use case? because I cannot come up with anything that does not need `apply_filters('the_content',...)`

wp overhead was never a problem so far. Typically it is more common that a plugin is badly / slow performance written, and that causes problems.

the access to functions of wordpress are very 2000. The whole wordpress framework is old looking. No programmer wants to use it, if it is possible to avoid it. I chose corcel because it lets me write stuff quicker, and makes me happy when using it. Why you are against using both together and only falling back to pure wp, I dont really understand

**Comment by Jossnaz** [comment]
btw i am writing this because I yet solved another issue when loading both together. And I thought this would be a good place to share it with other devs, but as I understand, that knowledge is not wanted here

**Comment by jgrossi** [comment]
@Jossnaz there's no right or wrong here, just recommendations... if you're including WP file to add all classes and functions it has you don't need Corcel, just get the posts you need using `get_posts()` for example... it's now about "ugly" or "beautiful" but what works better for you...

If you want to use Corcel you're going to use Laravel stuff, not WP... you won't use WP routes, templates, filters, actions, nothing, you can do similar stuff in Laravel using OOP:

```php
// routes.php

Route::get('/posts', 'PostsController@index');

// PostsController.php

use Corcel\Post as Post;

class PostsController extends Controller
{
    public function index()
    {
        $posts = Post::orderBy('post_title')->get(); // here I'm using Corcel

        return view('posts.index', compact('posts'));
    }
}

// posts/index.blade.php

<h1>Posts</h1>
<ul>
    @foreach($posts as $post)
        <li>{{ $post->post_title }}</li>
    @endforeach
</ul>
```

That's the recommended way to use Corcel, acting like it was the Model layer in a Laravel app. 

JG
