### ISSUE TITLE
Corcel + L5.4 

### ISSUE THREAD

**Issue by codepotato** [corcel/corcel#266]
Hi all, thanks for developing Corcel, it'll save me hours! 

That said, I'm having a problem at the moment with authenticating. I've followed all the setup tips for laravel and i'm getting this error: 

Column not found: 1054 Unknown column 'email' in 'where clause' (SQL: select * from `wp_users` where `email` = {email}

I'm running Laravel 5.4 with two databases, one for laravel's own bits (files etc) and another that is a full wordpress install with existing data. 

Any ideas? Appreciate this is quite vague but i'm stumped!

**Comment by codepotato** [comment]
My auth.php config is : 

'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
        ],
    ],

'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => \Corcel\User::class,
        ],

**Comment by rundef** [comment]
Hi,

When are you getting this error ? When you are trying to login ?

Have a look at my [AuthController](https://github.com/rundef/laravel_wordpress/blob/tutorial2/site/app/Http/Controllers/Site/Auth/AuthController.php), it's a bit different than the one that comes with Laravel.

**Comment by codepotato** [comment]
Hi @rundef this is when I'm using the standard laravel auth view. I assumed this would tie in with the AuthServiceProvider that ships with this package?

**Comment by codepotato** [comment]
It's looking at the right table, but doesn't seem to touch the Corcel logic.

**Comment by codepotato** [comment]
That AuthController isn't used in Laravel 5.4?

**Comment by rundef** [comment]
My bad this is actually for laravel 5.2

But your config is wrong, take a look [here](https://github.com/corcel/corcel#using-laravel)

You need to register the **AuthServiceProvider** and use '`driver' => 'corcel'` in your config/auth.php file

**Comment by codepotato** [comment]
I've done both of those, too.

**Comment by codepotato** [comment]
Oops! I eat my words! I had missed the part about changing the driver to corcel. Oops. Thanks for the help!
