### ISSUE TITLE
Paginate Terms

### ISSUE THREAD

**Issue by jigsawsoul** [corcel/corcel#267]
Hi,

How can I paginate the posts from a category?
```Category::slug($slug)->posts()->paginate();```

Many thanks

**Comment by jgrossi** [comment]
@jigsawsoul hi! isn't `->posts()->paginate()` working?

**Comment by jigsawsoul** [comment]
Erm, I was sure it wasn't, but it is now

**Comment by jigsawsoul** [comment]
@jgrossi how can I only show published posts of the category, right now I have revisions also, I have tried adding `->published()`

**Comment by jgrossi** [comment]
`->posts()->published()->paginate()` should work.

**Comment by thanhtutoo** [comment]
$posts = Post::published()->get();
return $posts;

if i use like this, it show the error like this

> BadMethodCallException in Builder.php line 2451:
Call to undefined method Illuminate\Database\Query\Builder::published()


 But if i use like this


>    $posts = Post::all();
return $posts;

it works.Help me out please. Thanks.

**Comment by jgrossi** [comment]
@thanhtutoo is `Post::published()->get()` not working???
