### ISSUE TITLE
Taylor broke belongsToMany again

### ISSUE THREAD

**Issue by jjiko** [corcel/corcel#268]
[fix various problems with belongs to many (#18380)](https://github.com/laravel/framework/commit/3aa2adc7574b0ff6f4f3b3a75de4b3f9c19a9737)

The constructor variables have changed and been renamed as of 3/16

In Model.php:128

This is the new belongToMany

        /**
         * Define a many-to-many relationship.
         *
         * @param  string  $related
         * @param  string  $table
         * @param  string  $foreignPivotKey
         * @param  string  $relatedPivotKey
         * @param  string  $parentKey
         * @param  string  $relatedKey
         * @param  string  $relation
         * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
         */
        public function belongsToMany($related, $table = null, $foreignPivotKey = null, $relatedPivotKey = null,
                                      $parentKey = null, $relatedKey = null, $relation = null)
        {
            // If no relationship name was passed, we will pull backtraces to get the
            // name of the calling function. We will use that function name as the
            // title of this relation since that is a great convention to apply.
            if (is_null($relation)) {
                $relation = $this->guessBelongsToManyRelation();
            }

            // First, we'll need to determine the foreign key and "other key" for the
            // relationship. Once we have determined the keys we'll make the query
            // instances as well as the relationship instances we need for this.
            $instance = $this->newRelatedInstance($related);

            $foreignPivotKey = $foreignPivotKey ?: $this->getForeignKey();

            $relatedPivotKey = $relatedPivotKey ?: $instance->getForeignKey();

            // If no table name was provided, we can guess it by concatenating the two
            // models using underscores in alphabetical order. The two model names
            // are transformed to snake case from their default CamelCase also.
            if (is_null($table)) {
                $table = $this->joiningTable($related);
            }

            return new BelongsToMany(
                $instance->newQuery(), $this, $table, $foreignPivotKey,
                $relatedPivotKey, $parentKey ?: $this->getKeyName(),
                $relatedKey ?: $instance->getKeyName(), $relation
            );
        }

Actually, I'm unsure as to why this function is being overwritten. It seems to work fine without the override. It might be more appropriate to remove your override since Taylor likes to change these functions and break this.

**Comment by jgrossi** [comment]
Hi @jjiko thanks for sharing this.

Actually, we maintain these methods because of previous versions of Laravel. For L5.1, 5.2 and 5.3 these relation methods did not take care of database connections, since 5.4 he changed that, so maintaining this is important for 5.1, 5.2 and 5.3 compatibilities.

I'm gonna get some time to check the changes and work on a bugfix for that. If you have any idea please send us a PR, ok? Thanks!
