### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by kevinkiel** [corcel/corcel#269]
I was wondering is there any search functionality like
Post::search('keyword')->get() ?

**Comment by jgrossi** [comment]
Hi @kevinkiel actually no. Once Corcel is based on Eloquent it's trivial to search between fields and tables, but maybe a simple search functionality would be great.

What are your thoughts about this search? Which fields?

**Comment by kevinkiel** [comment]
@jgrossi It would be great it you can set your own fields. But the basic is post_title and post_content (wp_posts) and maybe some connected ACF fields.

**Comment by marcoboom** [comment]
@kevinkiel In fact, the models are compatible with Laravel Scout.

**Comment by jgrossi** [comment]
@kevinkiel any update?
