### ISSUE TITLE
Sharing Login between Wordpress and Laravel App.

### ISSUE THREAD

**Issue by bstarr322** [corcel/corcel#270]
Hi @jgrossi ,

I 'd like you to explain about the Auth Sharing feature of Corcel.
I 'd like to login to Laravel app using Wordpress login credentials.
But It's not working well. Laravel app is based on Gentelella theme.

So I 'd like you to clarify this Auth Part.

Thanks

**Comment by jgrossi** [comment]
Hi @bstarr322 thanks for the comment. Actually, you have to use the `AuthServiceProvider` we provide to make possible logging into a Laravel installation with WP credentials.

What problem are you facing?

**Comment by SecretSquirrel001** [comment]
I tried to setup the plugin but I am receiving the following error,

QueryException in Connection.php line 647:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'user_email' in 'where clause' (SQL: select * from `users` where `user_email` = test@test.com order by `user_registered` desc limit 1)

the Laravel DB is the same as the WP Database

**Comment by jgrossi** [comment]
@SecretSquirrel001 sorry for the late response. Did you fix that? Where you trying to query by the correct column?

**Comment by bstarr322** [comment]
@jgrossi I was able to make it work without using this Package.
I created two db connections, and compared the wp password and laravel pass by using this package.
https://packagist.org/packages/mikemclin/laravel-wp-password

Thanks for your package.

**Comment by jgrossi** [comment]
@bstarr322 great! thanks for sharing!

**Comment by SecretSquirrel001** [comment]
@jgrossi yeah I forgot to change the database connections like a scrubby :D
