### ISSUE TITLE
How to switch options tables by site_id?

### ISSUE THREAD

**Issue by AstralProgrammer** [corcel/corcel#271]
Hi,

I'm trying to use Corcel together with a WP Multisite setup. I'm wondering how can I get the option details from other sites under the network? Is there something that works like switch_to_blog() ?

I tried displaying the entire result for the Options::all() but it only returns the options from the main options table which is for the main site only.

Thanks in advance.

**Comment by marcoboom** [comment]
@jgrossi @AstralProgrammer You could setup multiple database connections. For each site you only have to change the dbprefix property.

Within your AppServiceProvider you could select the current connection based on your domain or which settings you use.

Next you van change the wordpress/corcel db connection like:

```
$current = config('database.connections.mysite2');
config(['database.connections.wordpress'=>$current]);
```

**Comment by jgrossi** [comment]
@AstralProgrammer any update?

**Comment by AstralProgrammer** [comment]
Thanks for the responses.
I've create a new model instead. Inside that model, I set the db connection as an argument upon __construct()  which is set to wordpress by default like how @marcoboom mentioned. By doing so I could easily switch to other site inside the network. I did merge() on the results in cases that I needed aggregated data
