### ISSUE TITLE
Can I limit the fields to show?

### ISSUE THREAD

**Issue by AstralProgrammer** [corcel/corcel#272]
I tried using `$posts->get($array)` but it always returns with `Undefined property: stdClass::$post_type` . 
I don't think using a `$posts->pluck($field)` for every field should be the way to get them

**Comment by jgrossi** [comment]
Hi @AstralProgrammer I did not understand what you're trying to do, can you clarify a bit more? What are you trying to get?

**Comment by AstralProgrammer** [comment]
I'm trying to limit the fields that are return by the collection. Instead of giving the entire list, is there a way to just get multiple specified fields.
Currently $posts->pluck($thefield) works but is it possible to get multiple fields? Like $posts->get($array) where $array=[field1, field2] rather than have 2 plucks().

**Comment by Dartui** [comment]
@AstralProgrammer you should look first into Collection documentation. There is method named `only` which is doing exactly what you want: https://laravel.com/docs/5.4/collections#method-only
