### ISSUE TITLE
Pagination error

### ISSUE THREAD

**Issue by thaiscristine** [corcel/corcel#274]
When I call "$posts->render ()" I get the error:
`call_user_func() expects parameter 1 to be a valid callback, no array or string given (View: ...)`

ErrorException 
…/vendor/illuminate/pagination/AbstractPaginator.php412

My Controller:

if ($input->get('ajax'))
        {
            $posts  = Post::type('post')->published()->paginate(3);

            return view('blog.fragments.ajax', compact('posts'));
        }

the view:
`{!! $posts->render() !!}` or `{!! $posts->links() !!}` same error

Any idea what is the problem?

**Comment by jgrossi** [comment]
Hi @thaiscristine did you fix this? Sorry for the late response!

**Comment by thaiscristine** [comment]
No @jgrossi, I continue with this problem.

**Comment by jgrossi** [comment]
@thaiscristine I reproduced your code locally and it's working well. Are you using `Corcel\Post` class or your own? Have you set the correct database connection? When doing this:

```
$posts = Post::type('post')->published()->paginate(3);
```
Do you receive an instance of `LengthAwarePaginator`?

**Comment by jgrossi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix Post pagination issues](https://trello.com/c/ZE2qVG8P/20-fix-post-pagination-issues)

**Comment by jgrossi** [comment]
@thaiscristine any update?

**Comment by thaiscristine** [comment]
Yes, we are getting an instance of "LengthAwarePaginator". The problem is happening in the "$posts->render()".

**Comment by jgrossi** [comment]
@thaiscristine is this fixed in version 2?
