### ISSUE TITLE
Useless and obscure parameter in the AuthUserProvider

### ISSUE THREAD

**Issue by VijitCoder** [corcel/corcel#275]
```
AuthUserProvider::__construct($config)
```

`$this->config` is never used. Furthermore, it is not clear, what exactly should passed here. According the ["manual"](https://github.com/corcel/corcel#using-something-else), there is not expected any parameters.

**Comment by rundef** [comment]
Hi,

This parameter is only used when using Corcel with Laravel.
It contains the **config/auth.php** config and it's currently only used to create the right [user class instance](https://github.com/corcel/corcel/blob/master/src/Providers/AuthUserProvider.php#L105-L109).
If you are not using Laravel, then yeah it's kind of useless.

**Comment by VijitCoder** [comment]
> it's currently only used to create the right user class instance.

Oh! I do not understand how I missed it. The question is closed. Thanks.
