### ISSUE TITLE
Repeater dont work with Taxonomy 

### ISSUE THREAD

**Issue by SamuelNCarvalho** [corcel/corcel#276]
Repeater in taxonomy is not working.

Type error: Argument 2 passed to Corcel\Acf\Field\Repeater::fetchPostsMeta() must be an instance of Corcel\Post, instance of Corcel\Term given, called in D:\Samuel\Jobs\Giraffas\source\laravel\vendor\corcel\acf\src\Field\Repeater.php on line 30.

Code: 
```
$category = Taxonomy::with('parentTerm')->with('term')->whereHas('term', function($query) use ($categorySlug){
            $query->whereSlug($categorySlug);
        })->first();

$category->acf->repeater('repeater_field');
```
What is wrong?

**Comment by SamuelNCarvalho** [comment]
I made the fix for this issue. See in the code below:

In Corcel\Acf\Field\Repeater;

```
protected function fetchPostsMeta($fieldName, $post)
    {
        $count = (int) $this->fetchValue($fieldName);
        
        if($this->postMeta instanceof Term){
            $builder = $this->postMeta->where('post_id', $post->ID);    
        } else {
            $builder = $this->postMeta->where('term_id', $post->term_id);
        }

        $builder->where(function ($query) use ($count, $fieldName) {
            foreach (range(0, $count - 1) as $i) {
                $query->orWhere('meta_key', 'like', "{$fieldName}_{$i}_%");
            }
        });

        return $builder;
    }
```

**Comment by jgrossi** [comment]
hi @SamuelNCarvalho thanks for contributing! this is a issue related to the `corcel/acf` plugin, not the Corcel core. can you please make sure all `phpunit` tests are passing and then send there a new PR? thanks ;-)

**Comment by SamuelNCarvalho** [comment]
Pull Request done in `corcel/acf`. Issue closed.
