### ISSUE TITLE
Save user meta

### ISSUE THREAD

**Issue by VijitCoder** [corcel/corcel#279]
Hi
As I see in the `Corcel\User` model, its meta stores only if the user record updates. I suggest to change the save method, so it can save meta for user insertion at one time:

```php
public function save(array $options = [])
{
        $result = parent::save($options);
        if ($result) {
            $this->meta->save($this->attributes[$this->primaryKey]);
        }
        return $result;
}
```

This code works well with any case of the user change.

**Comment by jgrossi** [comment]
Hi @VijitCoder thanks for contributing. Can you send a PR with that? Thanks!

**Comment by VijitCoder** [comment]
PR https://github.com/corcel/corcel/pull/280
