### ISSUE TITLE
Menu - hiding attributes from response

### ISSUE THREAD

**Issue by Drax74** [corcel/corcel#284]
I am trying to hide attributes from the query response to the menu model. I have tried with both setting the hidden and the visible array:

use Corcel\Menu as Corcel;
use Illuminate\Database\Eloquent\Model;

> class Menu extends Corcel
> {
> 		public $id;
> 		public $name;
> 		public $type;
> 		public $cmsId;
> 		protected $connection = 'wordpress';
> 
> 		protected $hidden = ['created_at', 'ping_status', 'to_ping', 'pinged', 'post_excerpt'];
> 		protected $visible = ['ID', 'post_name', 'post_parent', 'guid', 'title', 'meta'];
> }

But, I still see all of the attributes from the query.

**Comment by jgrossi** [comment]
Hi @Drax74 try to use the `$append` variable, please. Maybe it's that the problem. Let me know the results please.
