### ISSUE TITLE
New Trello board

### ISSUE THREAD

**Issue by jgrossi** [corcel/corcel#285]
Hello everyone,

If you want to contribute with Corcel now we have a Trello board to manage tasks, plan new features, fix bugs, etc. 

Trello board Corcel PHP - https://trello.com/b/9F9UfiOD/corcel-php.

If you have interest in joining the board just let me know your Trello username and I'll add you.

Best regards, JG

**Comment by jakobbuis** [comment]
I'm @jakobbuis on Trello 😄

**Comment by jgrossi** [comment]
@jakobbuis added! ;-)
