### ISSUE TITLE
Global scopes

### ISSUE THREAD

**Issue by kevinkiel** [corcel/corcel#286]
I'm using a BasePost that extends Corcel\Post. And I was wondering is there any support for global scopes? 

I would like to use something like this:

```
static::addGlobalScope('order', function (Builder $builder) {
    $builder->orderBy('post_date', 'asc');
});
```

<img width="804" alt="schermafbeelding 2017-06-30 om 15 48 35" src="https://user-images.githubusercontent.com/531113/27738421-92771c60-5dab-11e7-87c4-525d497018f3.png">

**Comment by jgrossi** [comment]
Hi @kevinkiel sorry about the delay. Can't you create your own scope?

```
public function scopeFoo(Builder $query) {}
```

**Comment by kevinkiel** [comment]
@jgrossi 

Thanks for your reaction no problems.

Yes I can create a local scope but that means that I have to call the scope every time
model->order()->get
and with a global scope you only have to call the model
model->get

But on your reaction I understand there is no support for global scopes yet? :P

**Comment by jgrossi** [comment]
Hi @kevinkiel got it. Yes, you can. Actually this is not related to Corcel itself, but with Laravel's Eloquent ORM. That's possible and you basically have to create a new `FooScope`class that implements the `ScopeInterface` interface.

You can follow this post. It's very helpful and can solve your problem ;-)

https://softonsofa.com/laravel-5-eloquent-global-scope-how-to/#disqus_thread

**Comment by jgrossi** [comment]
@kevinkiel I think you can use something like what you did but with your own class:

```php
static::addGlobalScope(new FooScope());
```

**Comment by jgrossi** [comment]
@kevinkiel actually this last one is an easier solution. Take a look at @AlnourAltegani answer here: https://laracasts.com/discuss/channels/general-discussion/laravel-global-scope-on-retrieving-a-model

**Comment by Dartui** [comment]
Another approach:
```php
public function newQuery() {
	return parent::newQuery()->orderBy( 'post_date', 'asc' );
}
```

**Comment by jgrossi** [comment]
@kevinkiel did this solve your problem?
