### ISSUE TITLE
Parent pages

### ISSUE THREAD

**Issue by benrolfe** [corcel/corcel#288]
When using parent pages, the WordPress `posts` table uses the `post_parent` column.

Has anyone written Laravel PHP code to handle multiple parent pages? I want one route/controller to handle the fetching of the correct page/post.

Eg: www.example.com/work/case-studies/apple/

Is there a way to do this with the `hasOne` method?

**Comment by jgrossi** [comment]
Hi @benrolfe do you want to list all parent pages you have? The following logic is valid for any post type (post, page, custom, etc). If that's it:

```php
$parentPosts = Post::where('post_parent', 0)->get();
```
If you want to fetch the parent of a specific post just do this. You have a `parent()` relation you can use just calling `$post->parent`:
```php
$post = Post::find(1);
echo $post->parent->title;
```
But if you want all posts/pages that has parents:
```php
$posts = Post::where('parent_post', '>', 0)->get();
```

**Comment by benrolfe** [comment]
@jgrossi, it's very helpful to know about `$post->parent`, however I was more looking for an efficient way to write this...

```
Route::get('{grandparent_slug}/{parent_slug}/{child_slug}', function ($grandparent_slug, $parent_slug, $child_slug) {

});
```
I hope that clarifies the question.

**Comment by jgrossi** [comment]
Well, inside this route you should query the page you want, just write a Laravel query to fetch the page by the `$child_slug` and others variable (maybe you should use multiple `whereHas()` to match the `parent_slug` and then `grandparent_slug`, if you find the page ok, if not, you trigger a 404 response.

If you want to do something automatically, with multilevels you still can do this, but you have to update your query to reach the parent limit...

**Comment by benrolfe** [comment]
I've got this to work...

```
Route::get('{grandparent_slug}/{parent_slug?}/{child_slug?}', function ($grandparent_slug, $parent_slug = null, $child_slug = null) {

    $slugs = Route::getCurrentRoute()->parameters();

    $id = null;

    foreach ($slugs as $slug)
    {
        $post = App\Post::where('post_name', $slug)
            ->type('page')
            ->status('publish');

        if ($id)
        {
            $post->where('post_parent', $id);
        }

        $post = $post->firstOrFail();

        $id = $post->id;
    }

    $slug = (View::exists($slug) ? $slug : 'default');

    return view($slug, [
        'post' => $post
    ]);
});
```

**Comment by jgrossi** [comment]
@benrolfe nice approach ;-) anything I can help just let me know! Cheers!
