### ISSUE TITLE
How to access the post permalink?

### ISSUE THREAD

**Issue by Samnan** [corcel/corcel#290]
Tried

{{ $post->url }}   // gives something like blog/?p=1

Need the rest url for the post..

**Comment by jgrossi** [comment]
Hi, @Samnan thanks for sharing.

Actually, once you're using WordPress inside another app does not make sense to use post permalink. The post permalink should be related to your app's routes.

For example, if you have a `/post/{slug}` route in Laravel called `post.show` you should get the permalink with something like this:
```php
<a href="{{ route('post.show', $post->ID) }}">Link to post</a>
```

**Comment by Samnan** [comment]
Hi, the way I am using corcel is to have wordpress its own blog and admin, and in my laravel website, I have setup custom post types in wordpress that I need to fetch and display in my main website. The reason for post permalink requirement is because i have to show the most recent blog posts also (along with their url) in the website homepage, and that's why the permalink is needed. Without the permalink, people will not be able to actually go to the blog post. Although i can get the unclean url from post, I really need the permalink format.

Any help is appreciated in this regard.

**Comment by jgrossi** [comment]
Well, in this case, you should create a helper function to build the WP permalink, getting the URL from the WordPress install (from database) and then appending the `$post->url`. 

You have to think you're dealing with two different apps, connects only by the database. Another options would be creating a `getPermalinkAttribute()` in your own `Post`class to generate the URL, getting the URL from WP database (`wp_options`) and appending the `$post->url`.

**Comment by Samnan** [comment]
That looks to be the only one of two ways to get the permalink. The other one requires loading wp-load.php, but that loads the whole wordpress as a library into the app, which is an overkill.

I will see what I can do. Thanks anyway!

**Comment by jgrossi** [comment]
Both options: 1) creating a helper function and 2) creating the permalink attribute on `Post` class you don't need to load WP (`wp-load.php`) just use Corcel to get the WP url (`Options` class) and append the post url.

**Comment by macedd** [comment]
```php
use Corcel\Model\Option;
$siteUrl = Option::get('siteurl');
```
