### ISSUE TITLE
Meta relation error

### ISSUE THREAD

**Issue by kalinichenko88** [corcel/corcel#291]
I got an error If use own class for custom post type.

Example:

```
use Corcel\Model\Post as Corcel;

class Video extends Corcel
{
    protected $postType = 'video';
}
```

Any query returns exception:

```
QueryException

  #sql: "select * from `wp_postmeta` where `video_id` in (?, ?)"
  #bindings: array:2 [▼
    0 => 2
    1 => 287
  ]
  #message: "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'video_id' in 'where clause' (SQL: select * from `wp_postmeta` where `video_id` in (2, 287))"
```

I found problem in https://github.com/corcel/corcel/blob/2.4/src/Traits/HasMetaFields.php#L184 , relation field builds dynamic based on class name, but it should be 'post_id' always.

Is it bug or feature?

used corcel 2.4

**Comment by jgrossi** [comment]
@kalinichenko88 thank you so much for this.. that's a bug and I did not think in that case, a custom post that has meta fields ;-) it's not tested actually, but I'm gonna do that and merge..

and thanks for trying the `2.4` branch ;-) it's going to be release soon.

are you using Laravel 5.4, right?

**Comment by jgrossi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix bug when a custom post type has meta](https://trello.com/c/J1jONXgr/45-fix-bug-when-a-custom-post-type-has-meta)

**Comment by jgrossi** [comment]
@kalinichenko88 it's fixed on `2.4` branch. can you update and check if it's working now, please?

**Comment by kalinichenko88** [comment]
@jgrossi it's worked. Thanks!

I use Corcel with Laravel 5.4. Also, I trying use Corcel in WordPress plugin development

**Comment by jgrossi** [comment]
@kalinichenko88 cool stuff! let me know any bugs or question ;-)

**Comment by jgrossi** [comment]
@kalinichenko88 are you using `2.4` branch, right? did you find any bug? I'm about to tag `2.4.0` ;-)

**Comment by kalinichenko88** [comment]
@jgrossi thanks for your attention! I using 2.4 branch. No new bugs yet :-) looks fine
