### ISSUE TITLE
ACF & relational post object

### ISSUE THREAD

**Issue by omzy83** [corcel/corcel#294]
I have created a field in ACF called "case study". The field is of type "Post". I use this field for a section on my homepage that displays a case study. Screenshot to illustrate:

![image](https://user-images.githubusercontent.com/8927010/29005324-d05ea330-7ad0-11e7-8dcd-fa9ffdee12a8.png)

app/Http/Controllers/HomeController.php:

```
<?php

namespace App\Http\Controllers;

use App\Models\Post;

class HomeController extends Controller
{
    public function index()
    {
        $post = Post::slug('home')->firstOrFail();
        
        // this is the name of my custom field which is custom post type 'Case Study'
        $case_study = $post->acf->case_study; 

        return view('pages.home', [
            'post' => $post,
            'case_study' => $case_study,
        ]);
    }
}
```

app/Models/CaseStudy.php

```
<?php

namespace App\Models;

class CaseStudy extends \Corcel\Post
{
    public function getImage()
    {
        return $this->thumbnail->size('large');
    }
}
```

What I want to do in my front end is output the custom field, along with the related post featured image. This works fine, as follows:

`echo $case_study->thumbnail;`

What I want to do however, is output the image from the `getImage()` function in my `CaseStudy.php` file:

So I tried the following:

`echo $case_study->getImage();`

I get the error: `Call to undefined method Illuminate\Database\Query\Builder::getImage()`

Does anyone know what I need to do to make this work?

**Comment by omzy83** [comment]
Anyone able to help?

**Comment by p-drolima** [comment]
can u paste the code here?

**Comment by omzy83** [comment]
@p-drolima I've just updated my original post with the relevant code.

**Comment by jgrossi** [comment]
@omzy83 what's the instance type of the `$case_study` object? is it really a `Builder` instance?

**Comment by omzy83** [comment]
As far as I know, `$case_study` is a CaseStudy post type.

What it seems like to me is that it's not able to access any methods in my CaseStudy model.

**Comment by jgrossi** [comment]
It should be a `Post` instance but it seems to be a `Builder` one. did you debug it?

**Comment by omzy83** [comment]
I did a `dd()` of `$case_study` and here is the output:

![image](https://user-images.githubusercontent.com/8927010/29032278-ba0fe900-7b88-11e7-8af7-a3b73879a450.png)

Is there any better way to debug?

**Comment by Dartui** [comment]
I think that this is related to #250. `$post->acf->case_study` returns base class `Post`, not your extended CaseStudy.

**Comment by omzy83** [comment]
@Dartui thanks for pointing this out, it provided the solution for me.

I just needed to map the classes in `corcel.php`, e.g:

    'post_types' => [
        'case_studies' => App\Models\CaseStudy::class,
    ],
