### ISSUE TITLE
ACF connection error

### ISSUE THREAD

**Issue by omzy83** [corcel/corcel#295]
Just installed Corcel 2.4 and I'm getting an error right away. I'm trying to access an ACF field, the error I am getting is:

![image](https://user-images.githubusercontent.com/8927010/28994864-623e262e-79d0-11e7-83ee-10dd7474beae.png)

I have set up the database connection in `config/corcel.php`. I don't get the error when I remove the ACF fields.

I have extended my own Post class as follows:

```
<?php

namespace App\Models;

class Post extends \Corcel\Model\Post
{
    public function getPageMetaData()
    {
        $meta_title = $this->acf->text('meta_title');
        $meta_description = $this->acf->text('meta_description');

        return [
            'meta_title' => $meta_title,
            'meta_description' => $meta_description,
        ];
    }
}
```

**Comment by jgrossi** [comment]
@omzy83 hi thanks for reporting this. For now you can get the ACF field as `$post->meta->field_name`. I'm gonna check this issue and let you know.

**Comment by omzy83** [comment]
Thanks @jgrossi . I just found that the issue is due to the namespacing in the corcel/acf package. E.g in `BasicField.php` it has:

```
use Corcel\Post;
use Corcel\Model;
use Corcel\PostMeta;
use Corcel\Term;
use Corcel\TermMeta;
```

it should be:

```
use Corcel\Model\Post;
use Corcel\Model;
use Corcel\Model\Meta\PostMeta;
use Corcel\Model\Term;
use Corcel\Model\Meta\TermMeta;
```

**Comment by jgrossi** [comment]
@omzy83 hm good call. Can you send a PR to `corcel/acf` I'm AFK.

**Comment by omzy83** [comment]
Done. https://github.com/corcel/acf/pull/47

I'm guessing you'll need to create a new major version of ACF for Corcel v2?

**Comment by jgrossi** [comment]
@omzy83 thanks for contributing. ACF plugin is now version `1.0.0` and all phpunit tests fixed ;-) thanks
