### ISSUE TITLE
using laravel models inside wordpress

### ISSUE THREAD

**Issue by vivek7890** [corcel/corcel#298]
How can I use laravel model inside wordpress. Can you give me one example. I need both way communication. I looked at this https://github.com/corcel/corcel/issues/270 and https://github.com/corcel/corcel/issues/246 but i din't get. Thanks

**Comment by jgrossi** [comment]
Hm you want to do the opposite, I guess. It's possible but in this case you should add composer in WP and then load the `illuminate/database` package, OR include Laravel's `bootstrap.php` file inside WP.

**Comment by aswin-giri** [comment]
I have used this in a plugin. You will have to use composer. 

composer require illuminate/database

And on plugin file do:


require PLUGIN_DIR_PATH.'/vendor/autoload.php';

/*database connection*/
$capsule = new Illuminate\Database\Capsule\Manager;
$capsule->addConnection([
        'driver'    => 'mysql',
        'host'      => DB_HOST,
        'database'  => DB_NAME,
        'username'  => DB_USER,
        'password'  => DB_PASSWORD,
        'charset'   => 'utf8',
        'collation' => 'utf8_unicode_ci',
        'prefix'    => '',
        ]);
$capsule->setAsGlobal();
$capsule->bootEloquent();

Now you have access to Eloquent. But by doing this you are making multiple database connection.

I have written an article on this topic, you can read more detailed instruction [here](https://wpdrift.com/blog/2017/07/21/using-eloquent-in-wordpress-plugin-development/)

**Comment by jgrossi** [comment]
Yep @ezoomllc actually you're using `illuminate/database` package as the `Capsule`, and this is exactly what Corcel does, but using its `Database` class wrapper.
