### ISSUE TITLE
Some attributes function are missing (Models/Post.php)

### ISSUE THREAD

**Issue by anujdhingra11** [corcel/corcel#299]
/**
     * Gets the title attribute.
     *
     * @return string
     */
    public function getTitleAttribute()
    {
        return $this->post_title;
    }

    /**
     * Gets the slug attribute.
     *
     * @return string
     */
    public function getSlugAttribute()
    {
        return $this->post_name;
    }
    /**
     * Gets the type attribute.
     *
     * @return string
     */
    public function getTypeAttribute()
    {
        return $this->post_type;
    }
    
    /**
     * Gets the mime type attribute.
     *
     * @return string
     */
    public function getMimeTypeAttribute()
    {
        return $this->post_mime_type;
    }
    
    /**
     * Gets the url attribute.
     *
     * @return string
     */
    public function getUrlAttribute()
    {
        return $this->guid;
    }
    
    /**
     * Gets the author id attribute.
     *
     * @return int
     */
    public function getAuthorIdAttribute()
    {
        return $this->post_author;
    }
    
    /**
     * Gets the parent id attribute.
     *
     * @return int
     */
    public function getParentIdAttribute()
    {
        return $this->post_parent;
    }
    /**
     * Gets the created at attribute.
     *
     * @return date
     */
    public function getCreatedAtAttribute()
    {
        return $this->post_date;
    }
    
    /**
     * Gets the updated at attribute.
     *
     * @return date
     */
    public function getUpdatedAtAttribute()
    {
        return $this->post_modified;
    }
    
    /**
     * Gets the status attribute.
     *
     * @return string
     */
    public function getStatusAttribute()
    {
        return $this->post_status;
    }

**Comment by jgrossi** [comment]
hi, no they aren't. take a look on the `aliases` attribute in `Post` class. cheers.
