### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::getTitleAttribute() when returning posts

### ISSUE THREAD

**Issue by yahyazini** [corcel/corcel#300]
I'm trying the following:
```
Route::get('posts', function () {
    return App\Post::all();
});
```
and getting the following error:
```
BadMethodCallException
Call to undefined method Illuminate\Database\Query\Builder::getTitleAttribute()
```

My model has nothing special and my connection is set in config/corcel.php:
```
<?php 

namespace App;

use Corcel\Model\Post as Corcel;

class Post extends Corcel
{
   
}
```

**Comment by anujdhingra11** [comment]
#Add below functions in Post.php

 /**
     * Gets the title attribute.
     *
     * @return string
     */
    public function getTitleAttribute()
    {
        return $this->post_title;
    }

    /**
     * Gets the slug attribute.
     *
     * @return string
     */
    public function getSlugAttribute()
    {
        return $this->post_name;
    }
    /**
     * Gets the type attribute.
     *
     * @return string
     */
    public function getTypeAttribute()
    {
        return $this->post_type;
    }
    
    /**
     * Gets the mime type attribute.
     *
     * @return string
     */
    public function getMimeTypeAttribute()
    {
        return $this->post_mime_type;
    }
    
    /**
     * Gets the url attribute.
     *
     * @return string
     */
    public function getUrlAttribute()
    {
        return $this->guid;
    }
    
    /**
     * Gets the author id attribute.
     *
     * @return int
     */
    public function getAuthorIdAttribute()
    {
        return $this->post_author;
    }
    
    /**
     * Gets the parent id attribute.
     *
     * @return int
     */
    public function getParentIdAttribute()
    {
        return $this->post_parent;
    }
    /**
     * Gets the created at attribute.
     *
     * @return date
     */
    public function getCreatedAtAttribute()
    {
        return $this->post_date;
    }
    
    /**
     * Gets the updated at attribute.
     *
     * @return date
     */
    public function getUpdatedAtAttribute()
    {
        return $this->post_modified;
    }
    
    /**
     * Gets the status attribute.
     *
     * @return string
     */
    public function getStatusAttribute()
    {
        return $this->post_status;
    }

**Comment by yahyazini** [comment]
Thanks, that did the trick!
So do I have to create accessors for each attribute in any custom model that mirrors a wp table?
Is this somewhere in the docs?

**Comment by jgrossi** [comment]
That's not necessary. The post class has a aliases property that maps those accessors with the correct attribute. Is this not working?

**Comment by yahyazini** [comment]
@jgrossi I definitely had to add all those accessors in order for my Post model to function correctly.

**Comment by bridgeport** [comment]
I'm also getting this same error even using an extended Page or Post class using Laravel v5.4.31 and Corcel v2.4.0. I'm also experiencing this error when calling Corcel directly within a controller, as such:

```
return \Corcel\Model\Page::all();
```

Here's what's being outputted in whoops:

```
\home\site\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php
```

```php
    /* ...
     * @param  string  $method
     * @param  array   $parameters
     * @return mixed
     *
     * @throws \BadMethodCallException
     */
    public function __call($method, $parameters)
    {
        if (static::hasMacro($method)) {
            return $this->macroCall($method, $parameters);
        }
 
        if (Str::startsWith($method, 'where')) {
            return $this->dynamicWhere($method, $parameters);
        }
 
        $className = static::class;
 
        throw new BadMethodCallException("Call to undefined method {$className}::{$method}()");
    }
```

Arguments:
```
"Call to undefined method Illuminate\Database\Query\Builder::getTitleAttribute()"
```

Thanks.

**Comment by Dartui** [comment]
Simplest way to reproduce:
```php
Post::all()->toArray();
```
That error occurs because of `title`, `slug`,  and others are in `appends` variable. Here you can look how Laravel treats that appended keys: https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L101

**Comment by Dartui** [comment]
@yahyazini @anujdhingra11 @bridgeport could you check dev branch if this is working? Thanks in advance

**Comment by bridgeport** [comment]
@Dartui This fixes it for me. Thanks.

**Comment by yahyazini** [comment]
@Dartui, that did it!
