### ISSUE TITLE
Create posts

### ISSUE THREAD

**Issue by omzy83** [corcel/corcel#301]
Is it possible to create posts using Corcel? I cannot find any documentation in relation to this.

**Comment by jgrossi** [comment]
Hi you can do anything Eloquent does, like `Post::create()`. Check Eloquent's documentation for more information.

**Comment by omzy83** [comment]
Thanks. But how do we add field data? For example I have a contact form, when you submit the form it should save all the fields such as first name, last name, email address, etc.

I know how to save with Eloquent but how do we save it in WordPress format?

**Comment by jgrossi** [comment]
Then you have to add post and post meta data. Meta is a relationship in Post class. 

```php
Post::create($postData)->meta()->create($metaData);
```

**Comment by interludic** [comment]
how to assign a post to a category?

**Comment by iteearmah** [comment]
> how to assign a post to a category?
$term_taxonomy_ids[2,3,4]
$post->taxonomies()->sync($term_taxonomy_ids);

**Comment by iteearmah** [comment]
Also how do we assign a featured image to a post?
