### ISSUE TITLE
Contact Form 7 integration

### ISSUE THREAD

**Issue by omzy83** [corcel/corcel#302]
I'm looking to integrate Contact Form 7 with Corcel. So for example I would create the form in CF7 and then output the form in my Laravel view, (possibly using the shorttag?).

Then I would submit the form back to CF7 which will provide a JSON validation response. If validation is OK then it would process the submission as normal.

Is this possible to do?

**Comment by jgrossi** [comment]
Why don't you use the ShortTage with Corcel? You'd have to just include it.

**Comment by jgrossi** [comment]
About the JSON response you can do that using Middlewares.
