### ISSUE TITLE
Keep getting Class 'Corcel\Post' not found

### ISSUE THREAD

**Issue by grafxflow** [corcel/corcel#309]
I have tried to implementing all the elements but keep getting.

`Class 'Corcel\Post' not found`

UPDATE: I have it working using the default.

`$posts = Corcel\Model\Post::all();`

but not the one below which I am guessing is an alias of the above.

`$posts = Post::all();`

**Comment by grafxflow** [comment]
Is this correct way when placing **post.php** in the **Controllers**?

`<?php
namespace App\Http\Controllers;

use Corcel\Model\Post as Corcel;

class Post extends Corcel
{
    protected $connection = 'wordpress';
}`

**Comment by Dartui** [comment]
Please read this: https://github.com/corcel/corcel#namespace-change. There is a bit of unchanged class namespaces in documentation

**Comment by grafxflow** [comment]
Yes above cheers.
