### ISSUE TITLE
A few questions regarding best practise

### ISSUE THREAD

**Issue by grafxflow** [corcel/corcel#310]
Hi,

If a person using WordPress and for example choose to press such things as preview I am guessing these options are lost. Or is it possible to change the default preview url to something I could create in Laravel?

https://www.cyberciti.biz/faq/php-wordpress-change-post-url-via-preview_post_link-filter/

Regarding categories and tags etc. These can still be automatic and there is no requirement for them to be added manually to the routes - so such things as /{category?}/ would work fine?

How would you differentiate between a page or category in a route like above? /{category1?}/ or /{page1?}/

How would you sort category inside another category?  /{category1?}/{category2?}/

**Comment by Dartui** [comment]
You have to implement almost everything by yourself: routings, controllers and views. Corcel gives you models (not only, but mostly) to interact with database.

To make your routing works you cannot use dynamic parameter as the first element after root of your website for everything (categories, tags, posts, pages...). You have to do it like Wordpress - put prefix before slug. This is how you can achieve that:

```php
Route::get('category/{category}', 'CategoryController@view'); // display all posts in category
Route::get('tags/{tag}', 'TagController@view'); // display all posts with tag
Route::get('post/{post}', 'PostController@view'); // display single post
Route::get('{page}', 'PageController@view'); // display single page
```

**Comment by jgrossi** [comment]
Maybe it would be nice to create a plugin or something like this to include some Laravel routes according the WP routes, but I guess letting this opened is better to allow the dev to customize these routes.

**Comment by Dartui** [comment]
Publishing resources via vendor:publish would be nice improvement
