### ISSUE TITLE
How to use Page Templates

### ISSUE THREAD

**Issue by MLDev2** [corcel/corcel#329]
I understand that Corcel is largely to help with DB stuff but what I don't understand is where I should be putting my page templates. In the admin, I can set a page to belong to a template, which would exist in the template-parts folder.
Laravel has its own views folder where layouts and views are stored. Should I be creating my templates in the wordpress folder or laravel folder? And how can I check what page template a given page is set to?
Coming from a themosis background, the routes file would allow wp specific route types to determine this.
(Big fan of Corcel BTW)

**Comment by Dartui** [comment]
Please look at this question: #310.

The most important thing about Corcel is that it does not load any WordPress files. Templates created in theme will be not recognized by Corcel, because they are WordPress templates, not Laravel.

To achieve something like different templates for pages you can get `_wp_page_template` page meta:
```php
$page = Page::find($id);
$template = $page->meta->_wp_page_template;
```
and then extend view based on this variable, for example
```blade
@if ($template == 'template-fullwidth.php')
    @extends('layouts.fullwidth')
@else
    @extends('layouts.default')
@endif
```
This is not the best way of doing this, but this should works.

In a few days I will try to create command (for example `php artisan make:corcel`) for publishing some default Laravel resources (routes, controllers, views).

**Comment by MLDev2** [comment]
@Dartui thanks for the response.

I have the following which returns a page with loads of meta:
```
    $page = Page::slug($slug)->with('attachment')->first();
    dd($page->meta->_wp_page_template);
```
but the `dd` returns null. Otherwise this would be a great solution for me. Also note that the list of templates to choose from (in the admin) is based on existing files in the `wp/template-parts` folder, yet I want to move my files into the laravel `views` folder (including templates).

If there is no immediate solution I look forward to the `make:corcel` implementation.

**Comment by Dartui** [comment]
Maybe something like this in `corcel.php` config would work?
```php
'templates' => [
	'default' => 'layouts.default',
	'template-fullwidth.php' => 'layouts.full_width',
	'template-withsidebar.php' => 'layouts.sidebar',
]
```
I will think about this :+1:

**Comment by MLDev2** [comment]
What I have done in config/view.php is this:
```
'paths' => [
        // resource_path('views'),
        base_path('/wordpress/wp-content/themes/mytheme/views')
],
```
which seems to be working if I put my templates in the wordpress folders (this could work for me). Still not getting any template info in the meta though.

**Comment by jgrossi** [comment]
@MLDev2 aren't your WP template files in the `public` directory? Maybe `base_path('public/...')`?

**Comment by MLDev2** [comment]
@jgrossi no I put the wordpress files in a root folder called `wordpress`. That works fine, I just cant determine what template needs to be used based on what is set in the admin. Really would like to get that working as it's the only thing stopping me use corcel on live sites.
Just to re-iterate:
`dd($page->meta->_wp_page_template);`
returns null

**Comment by jgrossi** [comment]
@MLDev2 did you check if there's a `_wp_page_template` (`meta_key`) in `wp_postmeta` table for that page?

**Comment by MLDev2** [comment]
@jgrossi Not specifically. I would not have to do that check in vanilla wordpress. I am assuming that if I set the page to have a Page Template in the admin, it should be available on the resultant query.

**Comment by jgrossi** [comment]
@MLDev2 I'm only asking you to check in the database if that record exists for the given post because Corcel works with the WP database, not WP logic. I did a local test, setting a custom page template for a custom page and it's getting the `_wp_page_template` normally.

**Comment by MLDev2** [comment]
@jgrossi Okay this is very embarrassing. I thought I would just try and set it up again and now I can see the `_wp_page_template` key in the page meta. I could have sworn it wasn't there before. Very sorry to waste your time. I'm now looking forward to developing further with this plugin.

**Comment by jgrossi** [comment]
@MLDev2 anything just let me know. Cheers.
