### ISSUE TITLE
Category-class missing: docs out of date?

### ISSUE THREAD

**Issue by jakobbuis** [corcel/corcel#330]
After upgrading to 2.4.0 I run into the problem that the Category cannot be found. However, it is still(?) [included in the readme file](https://github.com/corcel/corcel#cats): 

```php
// clean and simple all posts from a category
$cat = Category::slug('uncategorized')->posts()->first();
$cat->posts->each(function($post) {
    echo $post->post_title;
});
```

Should this be removed, or is the class missing for some other reason?

**Comment by Dartui** [comment]
As I mentioned in #309, documentation is a bit outdated.

`Category` is WordPress build-in `Taxonomy`. You can get category in two ways:
- get it directly from `Taxonomy` class (it will give you instance of `Taxonomy` class):
```php
$cat = Taxonomy::where('taxonomy', 'category')->slug('uncathegorized');
```
- extend base `Taxonomy` class (it will give you instance of `Category` class):
```php
namespace YourNamespace;

use Corcel\Model\Taxonomy;

class Category extends Taxonomy {
    protected $taxonomy = 'category';
}
```
and in controller
```php
use YourNamespace\Category;

class Foo {
    public function Bar() {
        $cat = Category::slug('uncathegorized')->get();
    }
}

**Comment by jakobbuis** [comment]
Ah, great. Thanks for the pointer :) I'll see if I can find the time to make some docs-PRs
