### ISSUE TITLE
Laravel 5.5

### ISSUE THREAD

**Issue by fjoho** [corcel/corcel#331]
Will this work with Laravel 5.5?

**Comment by jgrossi** [comment]
I guess no. We're working in the `2.5` branch to be compatible with Laravel 5.5. Corcel 2.4 is compatible with Laravel 5.4.

**Comment by fjoho** [comment]
When do you think it's ready?

**Comment by jgrossi** [comment]
I have to do make some tests passing for 5.5 yet. I don't have a ETA for that, but I hope in the next weeks.

**Comment by fjoho** [comment]
Is there something I can do to help?
