### ISSUE TITLE
Laravel 5.5 Support

### ISSUE THREAD

**Issue by florianflock** [corcel/corcel#333]
Hi @jgrossi, 

for better tracking, I have closed the pr and opened this issue.

Thanks for interacting so fast. I didn't dive deep into it. May be `\Corcel\Model` is necessary because of the custom relations? L5.5 is only changing method `Model::belongsToMany()`, as I can analyze. There is one more key.

Looking forward to your feedback! 😁

**Comment by smoothlikejazz** [comment]
Just ran into this today, thanks for creating @florianflock.

**Comment by CurtisSaunders** [comment]
I am also experiencing this issue with the belongsToMany method on Laravel 5.5

**Comment by jgrossi** [comment]
I'm gonna try to fix that today. If anyone can send a PR before that I really appreciate ;-)

**Comment by jgrossi** [comment]
@CurtisSaunders @smoothlikejazz can you test that with `2.5` branch? it seems all issues are fixed. just waiting for confirmation to tag the new release :P

**Comment by jgrossi** [comment]
`2.5.0` is now tagged ;-)

**Comment by smoothlikejazz** [comment]
Thanks @jgrossi, I was able to update my local environment and run my integration tests, everything is working for me.  Thanks again.

**Comment by jgrossi** [comment]
@smoothlikejazz nice! any bug let me know please ;-)
