### ISSUE TITLE
Do not extend PostMeta in other meta classes

### ISSUE THREAD

**Issue by Dartui** [corcel/corcel#335]
Now in `dev` branch, each meta class (`CommentMeta`, `TermMeta`, `UserMeta`) is extending `PostMeta` class. I allows to write strange code which is returning null rather than throwing errors:
```php
User::find(1)->meta->first()->taxonomy; // returns null
Comment::find(1)->meta->first()->post; // it will also return null, because CommentMeta belongs to Post through Comment class, not directly
```

I will make PR in near future which will move mutual code into base `Meta` class.

**Comment by jgrossi** [comment]
Got it.
