### ISSUE TITLE
PostMeta taxonomy method

### ISSUE THREAD

**Issue by Dartui** [corcel/corcel#336]
I am trying to understand what `taxonomy` method is doing in `PostMeta` class. It has totally no sense. Also I cannot find any reference in code to this method. Can it be deleted?

PR which include this change: https://github.com/corcel/corcel/commit/3ddba29cbdb003e7ec10a5be03568fd8d6bab941#diff-b6fb6ff99943caafe9209b56ee5e1b36R33

**Comment by jgrossi** [comment]
Actually, I think it's used to get taxonomy from meta values, that's the reason. This is old I guess, I don't remember really why it's there, but there's a reason :-) This is even marked as `@todo test` but it seems I forgot to take a look on that code.

**Comment by jgrossi** [comment]
Fixed with #337
