### ISSUE TITLE
Multilanguage

### ISSUE THREAD

**Issue by josec89** [corcel/corcel#66]
Hello,

It would be cool to integrate a multilanguage feature. The task would be, find a good multilanguage plugin, and get the posts in different languages. I think this would be great, as we could ask for posts in different languages. The problem is we will be stuck with the dependence of one particular plugin.

What do you think?

**Comment by J-Fricke** [comment]
I'd suggest if coupling it to a single plugin, write an interface and implement in a class using the plugin so that another implementation could be subbed in later.

**Comment by jgrossi** [comment]
I think WPML is the best multilanguage plugin for WP, am I right?

**Comment by jgbneatdesign** [comment]
Yes you're right. WPML is currently the best. I haven't started using the
package yet but I'm planning to do so in a future project. Very good job so
far!

**Comment by josec89** [comment]
I'd rather an open source - free plugin. Don't you agree? 

I think this can be a good option => [Polylang](https://wordpress.org/plugins/polylang/)
It's also One post per language

**Comment by jgrossi** [comment]
I have to admit I've never used Polylang before. I visited the link and it seems promising. Maybe it can be a good plugin instead of WPML. I've only used the last one so I cannot give you my opinion about both, but I'm gonna try Polylang :-)

**Comment by josec89** [comment]
Guys, I'm going to research+test some multilanguage plugins since a client needs it in his website, would you like it to be integrated in Corcel library once I find a good one? I could create a PR with the solution I get

**Comment by rundef** [comment]
Sounds cool !

But I personally think that Corcel should only be used for WordPress core functionalities and that all the stuff related to a WordPress plugin should be in a Corcel plugin as well. (otherwise we might end up with a huge and messy codebase)
Right now, this is the only [Corcel plugin](https://github.com/mattKendon/corcel-to-corcel) I'm aware of, perhaps it's a good starting point to see how we can make Corcel plugins ?

What do you think, @jgrossi ?

**Comment by jgrossi** [comment]
Hi guys! I agree with @rundef about the Corcel's size and goals, but I also agree with @josec89 that there are some necessary features to make Corcel more powerful and extendable, like multilanguage, SEO, etc.

Maybe it's time to move to an organization, setup the `corcel/corcel` as project core and start creating independent plugins, like `corcel/seo`, `corcel/translation`, `corcel/authentication`, etc. This should allow us to extend with a lot of new features, plugins for both Corcel and WordPress, etc.

Sounds good?

**Comment by rundef** [comment]
I like that idea. But since there are many Wordpress plugins that can do the same thing (but differently), maybe we could have namespaces such as `corcel/translation-{pluginname}`  (instead of just `corcel/translation`)

**Comment by jgrossi** [comment]
Sure thing @rundef :-)

**Comment by TheJohnzo** [comment]
Have a new multilingual project I'm working on, and I think Corcel is just the thing to tie it together.  Nice going!

Just a comment about Polylang, I've used it on some standalone WP sites and it's a great free multilingual solution.  @josec89 is right, because each post is saved as multiple posts (1 post per language version) it seems like it would be easy enough to reference each post via Post::find(etc...).  

I'm planning on implementing over the summer here, hopefully I can find something to contribute on this front.  

Cheers!

**Comment by jgrossi** [comment]
Hi @TheJohnzo. Looking forward to get news about that! ;-)

**Comment by Charl13** [comment]
This is not a permanent solution but it can be usefull for people using PolyLang.
```
class Post extends \Corcel\Post
{
    public function scopeTranslate($query, $language)
    {
      $models = $query->taxonomy('language', $language);
      return $models;
    }
}
```
Fetch posts for the translation en:
`Post::translate('en')`

**Comment by jgrossi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add support for WPML plugin for translation purposes](https://trello.com/c/Uwveaa8E/37-add-support-for-wpml-plugin-for-translation-purposes)

**Comment by yclaes** [comment]
@Charl13, do you know if it's possible to translate ONE post using their slug or ID?

**Comment by socheatsok78** [comment]
I have a test package extended from Corcel, that will treat WPML post translation nicely. I'm not sure if it works for you but it is what i'm currently using with my project. [socheatsok78/wpml](https://github.com/socheatsok78/wpml)

**Comment by jgrossi** [comment]
@socheatsok78 that'd be nice! if you can contribute, go ahead! we can create a plugin `corcel/wpml` for that 😎

**Comment by socheatsok78** [comment]
@jgrossi i'd love to. :+1:  Let me know if i could give a helping hand.

**Comment by FR6** [comment]
If it helps anyone, here is the code to get Posts translated in a specific language with the plugin WPML:

```
$language = 'fr';
$post_type = 'project';

$projects = Corcel\Model\Post::type($post_type)
    ->status('publish')
    ->newest()
    ->leftJoin('icl_translations AS tr', function($join){
        $join->on('posts.ID', '=', 'tr.element_id')
             ->where('tr.element_type', '=', "post_{$post_type}");
    })
    ->where('tr.language_code', '=', $language)
    ->get();
```

**Comment by jgrossi** [comment]
@FR6 can you share this creating a PR for us? Thanks!
